# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class CAAnimation < Cocoa::NSObject
    attach_singular_method :animation, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :defaultValueForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :isRemovedOnCompletion, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setRemovedOnCompletion, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setTimingFunction, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :shouldArchiveValueForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :timingFunction, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
