# generated by 'rake generate'
require 'cocoa/bindings/CAAnimation'
module Cocoa
  class CAAnimationGroup < Cocoa::CAAnimation
    attach_method :animations, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setAnimations, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
