# generated by 'rake generate'
require 'cocoa/bindings/CAPropertyAnimation'
module Cocoa
  class CABasicAnimation < Cocoa::CAPropertyAnimation
    attach_method :byValue, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :fromValue, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setByValue, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setFromValue, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setToValue, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :toValue, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
