# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class CAConstraintLayoutManager < Cocoa::NSObject
    attach_singular_method :layoutManager, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
