# generated by 'rake generate'
require 'cocoa/bindings/CALayer'
module Cocoa
  class CAGradientLayer < Cocoa::CALayer
    attach_method :colors, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :endPoint, :args=>0, :names=>[], :types=>[], :retval=>"{CGPoint=dd}"
    attach_method :locations, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setColors, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setEndPoint, :args=>1, :names=>[], :types=>["{CGPoint=dd}"], :retval=>"v"
    attach_method :setLocations, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setStartPoint, :args=>1, :names=>[], :types=>["{CGPoint=dd}"], :retval=>"v"
    attach_method :setType, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :startPoint, :args=>0, :names=>[], :types=>[], :retval=>"{CGPoint=dd}"
    attach_method :type, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
