# generated by 'rake generate'
require 'cocoa/bindings/CAAnimation'
module Cocoa
  class CAPropertyAnimation < Cocoa::CAAnimation
    attach_singular_method :animationWithKeyPath, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :isAdditive, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isCumulative, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :keyPath, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setAdditive, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setCumulative, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setKeyPath, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setValueFunction, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :valueFunction, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
