# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class CARemoteLayerClient < Cocoa::NSObject
    attach_method :clientId, :args=>0, :names=>[], :types=>[], :retval=>"I"
    attach_method :initWithServerPort, :args=>1, :names=>[], :types=>["I"], :retval=>"@"
    attach_method :invalidate, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :layer, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setLayer, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
