# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class CARemoteLayerServer < Cocoa::NSObject
    attach_method :serverPort, :args=>0, :names=>[], :types=>[], :retval=>"I"
    attach_singular_method :sharedServer, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
