# generated by 'rake generate'
require 'cocoa/bindings/CALayer'
module Cocoa
  class CAScrollLayer < Cocoa::CALayer
    attach_method :scrollMode, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :scrollToPoint, :args=>1, :names=>[], :types=>["{CGPoint=dd}"], :retval=>"v"
    attach_method :scrollToRect, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"v"
    attach_method :setScrollMode, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
