# generated by 'rake generate'
require 'cocoa/bindings/CALayer'
module Cocoa
  class CAShapeLayer < Cocoa::CALayer
    attach_method :fillColor, :args=>0, :names=>[], :types=>[], :retval=>"^{CGColor=}"
    attach_method :fillRule, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :lineCap, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :lineDashPattern, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :lineDashPhase, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :lineJoin, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :lineWidth, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :miterLimit, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :path, :args=>0, :names=>[], :types=>[], :retval=>"^{CGPath=}"
    attach_method :setFillColor, :args=>1, :names=>[], :types=>["^{CGColor=}"], :retval=>"v"
    attach_method :setFillRule, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setLineCap, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setLineDashPattern, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setLineDashPhase, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setLineJoin, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setLineWidth, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setMiterLimit, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setPath, :args=>1, :names=>[], :types=>["^{CGPath=}"], :retval=>"v"
    attach_method :setStrokeColor, :args=>1, :names=>[], :types=>["^{CGColor=}"], :retval=>"v"
    attach_method :setStrokeEnd, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setStrokeStart, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :strokeColor, :args=>0, :names=>[], :types=>[], :retval=>"^{CGColor=}"
    attach_method :strokeEnd, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :strokeStart, :args=>0, :names=>[], :types=>[], :retval=>"d"
  end
end
