# generated by 'rake generate'
require 'cocoa/bindings/CALayer'
module Cocoa
  class CATiledLayer < Cocoa::CALayer
    attach_singular_method :fadeDuration, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :levelsOfDetail, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :levelsOfDetailBias, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :setLevelsOfDetail, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setLevelsOfDetailBias, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setTileSize, :args=>1, :names=>[], :types=>["{CGSize=dd}"], :retval=>"v"
    attach_method :tileSize, :args=>0, :names=>[], :types=>[], :retval=>"{CGSize=dd}"
  end
end
