# generated by 'rake generate'
require 'cocoa/bindings/CAAnimation'
module Cocoa
  class CATransition < Cocoa::CAAnimation
    attach_method :endProgress, :args=>0, :names=>[], :types=>[], :retval=>"f"
    attach_method :filter, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setEndProgress, :args=>1, :names=>[], :types=>["f"], :retval=>"v"
    attach_method :setFilter, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setStartProgress, :args=>1, :names=>[], :types=>["f"], :retval=>"v"
    attach_method :setSubtype, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setType, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :startProgress, :args=>0, :names=>[], :types=>[], :retval=>"f"
    attach_method :subtype, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :type, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
