# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class CAValueFunction < Cocoa::NSObject
    attach_singular_method :functionWithName, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :name, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
