# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class CIContext < Cocoa::NSObject
    attach_method :clearCaches, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_singular_method :contextWithCGContext, :args=>2, :names=>[:options], :types=>["^{CGContext=}", "@"], :retval=>"@"
    attach_singular_method :contextWithCGLContext, [{:args=>4, :names=>[:pixelFormat, :colorSpace, :options], :types=>["^{_CGLContextObject=}", "^{_CGLPixelFormatObject=}", "^{CGColorSpace=}", "@"], :retval=>"@"}, {:args=>3, :names=>[:pixelFormat, :options], :types=>["^{_CGLContextObject=}", "^{_CGLPixelFormatObject=}", "@"], :retval=>"@"}]
    attach_method :createCGImage, [{:args=>2, :names=>[:fromRect], :types=>["@", "{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"^{CGImage=}"}, {:args=>4, :names=>[:fromRect, :format, :colorSpace], :types=>["@", "{CGRect={CGPoint=dd}{CGSize=dd}}", "i", "^{CGColorSpace=}"], :retval=>"^{CGImage=}"}]
    attach_method :createCGLayerWithSize, :args=>2, :names=>[:info], :types=>["{CGSize=dd}", "^{__CFDictionary=}"], :retval=>"^{CGLayer=}"
    attach_method :drawImage, [{:args=>3, :names=>[:atPoint, :fromRect], :types=>["@", "{CGPoint=dd}", "{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"v"}, {:args=>3, :names=>[:inRect, :fromRect], :types=>["@", "{CGRect={CGPoint=dd}{CGSize=dd}}", "{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"v"}]
    attach_method :reclaimResources, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :render, [{:args=>6, :names=>[:toBitmap, :rowBytes, :bounds, :format, :colorSpace], :types=>["@", "^v", "q", "{CGRect={CGPoint=dd}{CGSize=dd}}", "i", "^{CGColorSpace=}"], :retval=>"v"}, {:args=>4, :names=>[:toIOSurface, :bounds, :colorSpace], :types=>["@", "^{__IOSurface=}", "{CGRect={CGPoint=dd}{CGSize=dd}}", "^{CGColorSpace=}"], :retval=>"v"}]
  end
end
