# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class CIColor < Cocoa::NSObject
    attach_method :initWithColor, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
  end
end
