# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class CIDetector < Cocoa::NSObject
    attach_singular_method :detectorOfType, :args=>3, :names=>[:context, :options], :types=>["@", "@", "@"], :retval=>"@"
    attach_method :featuresInImage, [{:args=>1, :names=>[], :types=>["@"], :retval=>"@"}, {:args=>2, :names=>[:options], :types=>["@", "@"], :retval=>"@"}]
  end
end
