# generated by 'rake generate'
require 'cocoa/bindings/CIFeature'
module Cocoa
  class CIFaceFeature < Cocoa::CIFeature
    attach_method :hasLeftEyePosition, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :hasMouthPosition, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :hasRightEyePosition, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :hasTrackingFrameCount, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :hasTrackingID, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :leftEyePosition, :args=>0, :names=>[], :types=>[], :retval=>"{CGPoint=dd}"
    attach_method :mouthPosition, :args=>0, :names=>[], :types=>[], :retval=>"{CGPoint=dd}"
    attach_method :rightEyePosition, :args=>0, :names=>[], :types=>[], :retval=>"{CGPoint=dd}"
    attach_method :trackingFrameCount, :args=>0, :names=>[], :types=>[], :retval=>"i"
    attach_method :trackingID, :args=>0, :names=>[], :types=>[], :retval=>"i"
  end
end
