# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class CIFeature < Cocoa::NSObject
    attach_method :bounds, :args=>0, :names=>[], :types=>[], :retval=>"{CGRect={CGPoint=dd}{CGSize=dd}}"
    attach_method :type, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
