# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class CIFilter < Cocoa::NSObject
    attach_method :isEnabled, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :name, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setEnabled, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
