# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class CIFilterShape < Cocoa::NSObject
    attach_method :initWithRect, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"@"
    attach_method :insetByX, :args=>2, :names=>[:Y], :types=>["i", "i"], :retval=>"@"
    attach_method :intersectWith, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :intersectWithRect, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"@"
    attach_singular_method :shapeWithRect, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"@"
    attach_method :transformBy, :args=>2, :names=>[:interior], :types=>["{CGAffineTransform=dddddd}", "B"], :retval=>"@"
    attach_method :unionWith, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :unionWithRect, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"@"
  end
end
