# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class CIFilterGenerator < Cocoa::NSObject
    attach_method :classAttributes, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :connectObject, :args=>4, :names=>[:withKey, :toObject, :withKey], :types=>["@", "@", "@", "@"], :retval=>"v"
    attach_method :disconnectObject, :args=>4, :names=>[:withKey, :toObject, :withKey], :types=>["@", "@", "@", "@"], :retval=>"v"
    attach_method :exportKey, :args=>3, :names=>[:fromObject, :withName], :types=>["@", "@", "@"], :retval=>"v"
    attach_method :exportedKeys, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :filter, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :filterGenerator, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :filterGeneratorWithContentsOfURL, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :initWithContentsOfURL, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :registerFilterName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :removeExportedKey, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setAttributes, :args=>2, :names=>[:forExportedKey], :types=>["@", "@"], :retval=>"v"
    attach_method :setClassAttributes, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :writeToURL, :args=>2, :names=>[:atomically], :types=>["@", "B"], :retval=>"B"
  end
end
