# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class CIImageAccumulator < Cocoa::NSObject
    attach_method :clear, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :extent, :args=>0, :names=>[], :types=>[], :retval=>"{CGRect={CGPoint=dd}{CGSize=dd}}"
    attach_method :format, :args=>0, :names=>[], :types=>[], :retval=>"i"
    attach_method :image, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :imageAccumulatorWithExtent, [{:args=>2, :names=>[:format], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}", "i"], :retval=>"@"}, {:args=>3, :names=>[:format, :colorSpace], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}", "i", "^{CGColorSpace=}"], :retval=>"@"}]
    attach_method :initWithExtent, [{:args=>2, :names=>[:format], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}", "i"], :retval=>"@"}, {:args=>3, :names=>[:format, :colorSpace], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}", "i", "^{CGColorSpace=}"], :retval=>"@"}]
    attach_method :setImage, [{:args=>1, :names=>[], :types=>["@"], :retval=>"v"}, {:args=>2, :names=>[:dirtyRect], :types=>["@", "{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"v"}]
  end
end
