# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class CIPlugIn < Cocoa::NSObject
    attach_singular_method :loadAllPlugIns, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_singular_method :loadNonExecutablePlugIns, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_singular_method :loadPlugIn, [{:args=>2, :names=>[:allowExecutableCode], :types=>["@", "B"], :retval=>"v"}, {:args=>2, :names=>[:allowNonExecutable], :types=>["@", "B"], :retval=>"v"}]
  end
end
