# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class CIVector < Cocoa::NSObject
    attach_method :W, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :X, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :Y, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :Z, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :count, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :initWithString, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :initWithValues, :args=>2, :names=>[:count], :types=>["^d", "Q"], :retval=>"@"
    attach_method :initWithX, [{:args=>1, :names=>[], :types=>["d"], :retval=>"@"}, {:args=>2, :names=>[:Y], :types=>["d", "d"], :retval=>"@"}, {:args=>3, :names=>[:Y, :Z], :types=>["d", "d", "d"], :retval=>"@"}, {:args=>4, :names=>[:Y, :Z, :W], :types=>["d", "d", "d", "d"], :retval=>"@"}]
    attach_method :stringRepresentation, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :valueAtIndex, :args=>1, :names=>[], :types=>["Q"], :retval=>"d"
    attach_singular_method :vectorWithString, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :vectorWithValues, :args=>2, :names=>[:count], :types=>["^d", "Q"], :retval=>"@"
    attach_singular_method :vectorWithX, [{:args=>1, :names=>[], :types=>["d"], :retval=>"@"}, {:args=>2, :names=>[:Y], :types=>["d", "d"], :retval=>"@"}, {:args=>3, :names=>[:Y, :Z], :types=>["d", "d", "d"], :retval=>"@"}, {:args=>4, :names=>[:Y, :Z, :W], :types=>["d", "d", "d", "d"], :retval=>"@"}]
  end
end
