# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSAlert < Cocoa::NSObject
    attach_method :accessoryView, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :addButtonWithTitle, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :alertStyle, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_singular_method :alertWithError, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :alertWithMessageText, :args=>5, :names=>[:defaultButton, :alternateButton, :otherButton, :informativeTextWithFormat], :types=>["@", "@", "@", "@", "@"], :retval=>"@", :variadic=>true
    attach_method :beginSheetModalForWindow, :args=>4, :names=>[:modalDelegate, :didEndSelector, :contextInfo], :types=>["@", "@", ":", "^v"], :retval=>"v"
    attach_method :buttons, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :helpAnchor, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :icon, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :informativeText, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :layout, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :messageText, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :runModal, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :setAccessoryView, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setAlertStyle, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setHelpAnchor, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setIcon, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setInformativeText, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setMessageText, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setShowsHelp, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setShowsSuppressionButton, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :showsHelp, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :showsSuppressionButton, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :suppressionButton, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :window, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
