# generated by 'rake generate'
require 'cocoa/bindings/NSPropertyDescription'
module Cocoa
  class NSAttributeDescription < Cocoa::NSPropertyDescription
    attach_method :allowsExternalBinaryDataStorage, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :attributeType, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :attributeValueClassName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :defaultValue, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setAllowsExternalBinaryDataStorage, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setAttributeType, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setAttributeValueClassName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDefaultValue, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setValueTransformerName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :valueTransformerName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :versionHash, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
