# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSAutoreleasePool < Cocoa::NSObject
    attach_singular_method :addObject, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :addObject, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :drain, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_singular_method :showPools, :args=>0, :names=>[], :types=>[], :retval=>"v"
  end
end
