# generated by 'rake generate'
require 'cocoa/bindings/NSOperation'
module Cocoa
  class NSBlockOperation < Cocoa::NSOperation
    attach_method :addExecutionBlock, :args=>1, :names=>[], :types=>["@?"], :retval=>"v"
    attach_singular_method :blockOperationWithBlock, :args=>1, :names=>[], :types=>["@?"], :retval=>"@"
    attach_method :executionBlocks, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
