# generated by 'rake generate'
require 'cocoa/bindings/NSDate'
module Cocoa
  class NSCalendarDate < Cocoa::NSDate
    attach_singular_method :calendarDate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :calendarFormat, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :dateByAddingYears, :args=>6, :names=>["months", "days", "hours", "minutes", "seconds"], :types=>["q", "q", "q", "q", "q", "q"], :retval=>"@"
    attach_singular_method :dateWithString, [{:args=>2, :names=>["calendarFormat"], :types=>["@", "@"], :retval=>"@"}, {:args=>3, :names=>["calendarFormat", "locale"], :types=>["@", "@", "@"], :retval=>"@"}]
    attach_singular_method :dateWithYear, :args=>7, :names=>["month", "day", "hour", "minute", "second", "timeZone"], :types=>["q", "Q", "Q", "Q", "Q", "Q", "@"], :retval=>"@"
    attach_method :dayOfCommonEra, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :dayOfMonth, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :dayOfWeek, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :dayOfYear, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :descriptionWithCalendarFormat, [{:args=>1, :names=>[], :types=>["@"], :retval=>"@"}, {:args=>2, :names=>["locale"], :types=>["@", "@"], :retval=>"@"}]
    attach_method :descriptionWithLocale, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :hourOfDay, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :initWithString, [{:args=>1, :names=>[], :types=>["@"], :retval=>"@"}, {:args=>2, :names=>["calendarFormat"], :types=>["@", "@"], :retval=>"@"}, {:args=>3, :names=>["calendarFormat", "locale"], :types=>["@", "@", "@"], :retval=>"@"}]
    attach_method :initWithYear, :args=>7, :names=>["month", "day", "hour", "minute", "second", "timeZone"], :types=>["q", "Q", "Q", "Q", "Q", "Q", "@"], :retval=>"@"
    attach_method :minuteOfHour, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :monthOfYear, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :secondOfMinute, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :setCalendarFormat, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setTimeZone, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :timeZone, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :yearOfCommonEra, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :years, :args=>7, :names=>["months", "days", "hours", "minutes", "seconds", "sinceDate"], :types=>["^q", "^q", "^q", "^q", "^q", "^q", "@"], :retval=>"v"
  end
end
