# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSCache < Cocoa::NSObject
    attach_method :countLimit, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :evictsObjectsWithDiscardedContent, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :name, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :objectForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :removeAllObjects, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :removeObjectForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setCountLimit, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setEvictsObjectsWithDiscardedContent, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setObject, [{:args=>2, :names=>[:forKey], :types=>["@", "@"], :retval=>"v"}, {:args=>3, :names=>[:forKey, :cost], :types=>["@", "@", "Q"], :retval=>"v"}]
    attach_method :setTotalCostLimit, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :totalCostLimit, :args=>0, :names=>[], :types=>[], :retval=>"Q"
  end
end
