# generated by 'rake generate'
require 'cocoa/bindings/NSImageRep'
module Cocoa
  class NSCIImageRep < Cocoa::NSImageRep
    attach_method :CIImage, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :imageRepWithCIImage, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :initWithCIImage, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
  end
end
