# generated by 'rake generate'
require 'cocoa/bindings/NSScriptCommand'
module Cocoa
  class NSCloseCommand < Cocoa::NSScriptCommand
    attach_method :saveOptions, :args=>0, :names=>[], :types=>[], :retval=>"Q"
  end
end
