# generated by 'rake generate'
require 'cocoa/bindings/NSViewController'
module Cocoa
  class NSCollectionViewItem < Cocoa::NSViewController
    attach_method :collectionView, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :draggingImageComponents, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :imageView, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :isSelected, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :setImageView, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setSelected, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setTextField, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :textField, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
