# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSColorSpace < Cocoa::NSObject
    attach_method :CGColorSpace, :args=>0, :names=>[], :types=>[], :retval=>"^{CGColorSpace=}"
    attach_method :ICCProfileData, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :adobeRGB1998ColorSpace, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :availableColorSpacesWithModel, :args=>1, :names=>[], :types=>["q"], :retval=>"@"
    attach_method :colorSpaceModel, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :colorSyncProfile, :args=>0, :names=>[], :types=>[], :retval=>"^v"
    attach_singular_method :deviceCMYKColorSpace, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :deviceGrayColorSpace, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :deviceRGBColorSpace, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :genericCMYKColorSpace, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :genericGamma22GrayColorSpace, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :genericGrayColorSpace, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :genericRGBColorSpace, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithCGColorSpace, :args=>1, :names=>[], :types=>["^{CGColorSpace=}"], :retval=>"@"
    attach_method :initWithColorSyncProfile, :args=>1, :names=>[], :types=>["^v"], :retval=>"@"
    attach_method :initWithICCProfileData, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :localizedName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :numberOfColorComponents, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_singular_method :sRGBColorSpace, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
