# generated by 'rake generate'
require 'cocoa/bindings/NSView'
module Cocoa
  class NSCollectionView < Cocoa::NSView
    attach_method :allowsMultipleSelection, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :backgroundColors, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :content, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :draggingImageForItemsAtIndexes, :args=>3, :names=>[:withEvent, :offset], :types=>["@", "@", "^{CGPoint=dd}"], :retval=>"@"
    attach_method :frameForItemAtIndex, [{:args=>1, :names=>[], :types=>["Q"], :retval=>"{CGRect={CGPoint=dd}{CGSize=dd}}"}, {:args=>2, :names=>[:withNumberOfItems], :types=>["Q", "Q"], :retval=>"{CGRect={CGPoint=dd}{CGSize=dd}}"}]
    attach_method :isFirstResponder, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isSelectable, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :itemAtIndex, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_method :itemPrototype, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :maxItemSize, :args=>0, :names=>[], :types=>[], :retval=>"{CGSize=dd}"
    attach_method :maxNumberOfColumns, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :maxNumberOfRows, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :minItemSize, :args=>0, :names=>[], :types=>[], :retval=>"{CGSize=dd}"
    attach_method :newItemForRepresentedObject, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :selectionIndexes, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setAllowsMultipleSelection, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setBackgroundColors, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setContent, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDraggingSourceOperationMask, :args=>2, :names=>[:forLocal], :types=>["Q", "B"], :retval=>"v"
    attach_method :setItemPrototype, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setMaxItemSize, :args=>1, :names=>[], :types=>["{CGSize=dd}"], :retval=>"v"
    attach_method :setMaxNumberOfColumns, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setMaxNumberOfRows, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setMinItemSize, :args=>1, :names=>[], :types=>["{CGSize=dd}"], :retval=>"v"
    attach_method :setSelectable, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setSelectionIndexes, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
