# generated by 'rake generate'
require 'cocoa/bindings/NSPanel'
module Cocoa
  class NSColorPanel < Cocoa::NSPanel
    attach_method :accessoryView, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :alpha, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :attachColorList, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :color, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :detachColorList, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_singular_method :dragColor, :args=>3, :names=>["withEvent", "fromView"], :types=>["@", "@", "@"], :retval=>"B"
    attach_method :isContinuous, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :mode, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :setAccessoryView, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setAction, :args=>1, :names=>[], :types=>[":"], :retval=>"v"
    attach_method :setColor, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setContinuous, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setMode, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_singular_method :setPickerMask, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_singular_method :setPickerMode, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setShowsAlpha, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setTarget, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_singular_method :sharedColorPanel, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :sharedColorPanelExists, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :showsAlpha, :args=>0, :names=>[], :types=>[], :retval=>"B"
  end
end
