# generated by 'rake generate'
require 'cocoa/bindings/NSMutableSet'
module Cocoa
  class NSCountedSet < Cocoa::NSMutableSet
    attach_method :addObject, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :countForObject, :args=>1, :names=>[], :types=>["@"], :retval=>"Q"
    attach_method :initWithArray, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :initWithCapacity, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_method :initWithSet, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :objectEnumerator, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :removeObject, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
