# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSColorPicker < Cocoa::NSObject
    attach_method :attachColorList, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :buttonToolTip, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :colorPanel, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :detachColorList, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :initWithPickerMask, :args=>2, :names=>["colorPanel"], :types=>["Q", "@"], :retval=>"@"
    attach_method :insertNewButtonImage, :args=>2, :names=>["in"], :types=>["@", "@"], :retval=>"v"
    attach_method :minContentSize, :args=>0, :names=>[], :types=>[], :retval=>"{CGSize=dd}"
    attach_method :provideNewButtonImage, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setMode, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :viewSizeChanged, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
