# generated by 'rake generate'
require 'cocoa/bindings/NSControl'
module Cocoa
  class NSColorWell < Cocoa::NSControl
    attach_method :activate, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :color, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :deactivate, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :drawWellInside, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"v"
    attach_method :isActive, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isBordered, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :setBordered, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setColor, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :takeColorFrom, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
