# generated by 'rake generate'
require 'cocoa/bindings/NSScriptCommand'
module Cocoa
  class NSCreateCommand < Cocoa::NSScriptCommand
    attach_method :createClassDescription, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :resolvedKeyDictionary, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
