# generated by 'rake generate'
require 'cocoa/bindings/NSNotificationCenter'
module Cocoa
  class NSDistributedNotificationCenter < Cocoa::NSNotificationCenter
    attach_method :addObserver, [{:args=>4, :names=>[:selector, :name, :object], :types=>["@", ":", "@", "@"], :retval=>"v"}, {:args=>5, :names=>[:selector, :name, :object, :suspensionBehavior], :types=>["@", ":", "@", "@", "Q"], :retval=>"v"}]
    attach_singular_method :defaultCenter, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :notificationCenterForType, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :postNotificationName, [{:args=>2, :names=>[:object], :types=>["@", "@"], :retval=>"v"}, {:args=>3, :names=>[:object, :userInfo], :types=>["@", "@", "@"], :retval=>"v"}, {:args=>4, :names=>[:object, :userInfo, :deliverImmediately], :types=>["@", "@", "@", "B"], :retval=>"v"}, {:args=>4, :names=>[:object, :userInfo, :options], :types=>["@", "@", "@", "Q"], :retval=>"v"}]
    attach_method :removeObserver, :args=>3, :names=>[:name, :object], :types=>["@", "@", "@"], :retval=>"v"
    attach_method :setSuspended, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :suspended, :args=>0, :names=>[], :types=>[], :retval=>"B"
  end
end
