# generated by 'rake generate'
require 'cocoa/bindings/NSArrayController'
module Cocoa
  class NSDictionaryController < Cocoa::NSArrayController
    attach_method :excludedKeys, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :includedKeys, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initialKey, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initialValue, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :localizedKeyDictionary, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :localizedKeyTable, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :newObject, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setExcludedKeys, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setIncludedKeys, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setInitialKey, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setInitialValue, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setLocalizedKeyDictionary, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setLocalizedKeyTable, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
