# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSDistantObjectRequest < Cocoa::NSObject
    attach_method :connection, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :conversation, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :invocation, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :replyWithException, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
