# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSDockTile < Cocoa::NSObject
    attach_method :badgeLabel, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :contentView, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :display, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :owner, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setBadgeLabel, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setContentView, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setShowsApplicationBadge, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :showsApplicationBadge, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :size, :args=>0, :names=>[], :types=>[], :retval=>"{CGSize=dd}"
  end
end
