# generated by 'rake generate'
require 'cocoa/bindings/NSResponder'
module Cocoa
  class NSDrawer < Cocoa::NSResponder
    attach_method :close, [{:args=>0, :names=>[], :types=>[], :retval=>"v"}, {:args=>1, :names=>[], :types=>["@"], :retval=>"v"}]
    attach_method :contentSize, :args=>0, :names=>[], :types=>[], :retval=>"{CGSize=dd}"
    attach_method :contentView, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :edge, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :initWithContentSize, :args=>2, :names=>[:preferredEdge], :types=>["{CGSize=dd}", "Q"], :retval=>"@"
    attach_method :leadingOffset, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :maxContentSize, :args=>0, :names=>[], :types=>[], :retval=>"{CGSize=dd}"
    attach_method :minContentSize, :args=>0, :names=>[], :types=>[], :retval=>"{CGSize=dd}"
    attach_method :open, [{:args=>0, :names=>[], :types=>[], :retval=>"v"}, {:args=>1, :names=>[], :types=>["@"], :retval=>"v"}]
    attach_method :openOnEdge, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :parentWindow, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :preferredEdge, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :setContentSize, :args=>1, :names=>[], :types=>["{CGSize=dd}"], :retval=>"v"
    attach_method :setContentView, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setLeadingOffset, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setMaxContentSize, :args=>1, :names=>[], :types=>["{CGSize=dd}"], :retval=>"v"
    attach_method :setMinContentSize, :args=>1, :names=>[], :types=>["{CGSize=dd}"], :retval=>"v"
    attach_method :setParentWindow, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setPreferredEdge, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setTrailingOffset, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :state, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :toggle, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :trailingOffset, :args=>0, :names=>[], :types=>[], :retval=>"d"
  end
end
