# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSEnumerator < Cocoa::NSObject
    attach_method :allObjects, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :nextObject, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
