# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSEntityMapping < Cocoa::NSObject
    attach_method :attributeMappings, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :destinationEntityName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :destinationEntityVersionHash, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :entityMigrationPolicyClassName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :mappingType, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :name, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :relationshipMappings, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setAttributeMappings, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDestinationEntityName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDestinationEntityVersionHash, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setEntityMigrationPolicyClassName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setMappingType, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setRelationshipMappings, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setSourceEntityName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setSourceEntityVersionHash, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setSourceExpression, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setUserInfo, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :sourceEntityName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :sourceEntityVersionHash, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :sourceExpression, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :userInfo, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
