# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSEntityMigrationPolicy < Cocoa::NSObject
    attach_method :beginEntityMapping, :args=>3, :names=>[:manager, :error], :types=>["@", "@", "^@"], :retval=>"B"
    attach_method :createDestinationInstancesForSourceInstance, :args=>4, :names=>[:entityMapping, :manager, :error], :types=>["@", "@", "@", "^@"], :retval=>"B"
    attach_method :createRelationshipsForDestinationInstance, :args=>4, :names=>[:entityMapping, :manager, :error], :types=>["@", "@", "@", "^@"], :retval=>"B"
    attach_method :endEntityMapping, :args=>3, :names=>[:manager, :error], :types=>["@", "@", "^@"], :retval=>"B"
    attach_method :endInstanceCreationForEntityMapping, :args=>3, :names=>[:manager, :error], :types=>["@", "@", "^@"], :retval=>"B"
    attach_method :endRelationshipCreationForEntityMapping, :args=>3, :names=>[:manager, :error], :types=>["@", "@", "^@"], :retval=>"B"
    attach_method :performCustomValidationForEntityMapping, :args=>3, :names=>[:manager, :error], :types=>["@", "@", "^@"], :retval=>"B"
  end
end
