# generated by 'rake generate'
require 'cocoa/bindings/NSPropertyDescription'
module Cocoa
  class NSFetchedPropertyDescription < Cocoa::NSPropertyDescription
    attach_method :fetchRequest, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setFetchRequest, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
