# generated by 'rake generate'
require 'cocoa/bindings/NSExpression'
module Cocoa
  class NSFetchRequestExpression < Cocoa::NSExpression
    attach_method :contextExpression, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :expressionForFetch, :args=>3, :names=>[:context, :countOnly], :types=>["@", "@", "B"], :retval=>"@"
    attach_method :isCountOnlyRequest, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :requestExpression, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
