# generated by 'rake generate'
require 'cocoa/bindings/NSMatrix'
module Cocoa
  class NSForm < Cocoa::NSMatrix
    attach_method :addEntry, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :cellAtIndex, :args=>1, :names=>[], :types=>["q"], :retval=>"@"
    attach_method :drawCellAtIndex, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :indexOfCellWithTag, :args=>1, :names=>[], :types=>["q"], :retval=>"q"
    attach_method :indexOfSelectedItem, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :insertEntry, :args=>2, :names=>[:atIndex], :types=>["@", "q"], :retval=>"@"
    attach_method :preferredTextFieldWidth, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :removeEntryAtIndex, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :selectTextAtIndex, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setBezeled, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setBordered, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setEntryWidth, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setFrameSize, :args=>1, :names=>[], :types=>["{CGSize=dd}"], :retval=>"v"
    attach_method :setInterlineSpacing, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setPreferredTextFieldWidth, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setTextAlignment, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setTextBaseWritingDirection, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setTextFont, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setTitleAlignment, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setTitleBaseWritingDirection, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setTitleFont, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
