# generated by 'rake generate'
require 'cocoa/bindings/NSActionCell'
module Cocoa
  class NSFormCell < Cocoa::NSActionCell
    attach_method :attributedTitle, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initTextCell, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :isOpaque, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :placeholderAttributedString, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :placeholderString, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :preferredTextFieldWidth, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :setAttributedTitle, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setPlaceholderAttributedString, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setPlaceholderString, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setPreferredTextFieldWidth, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setTitle, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setTitleAlignment, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setTitleBaseWritingDirection, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setTitleFont, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setTitleWidth, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setTitleWithMnemonic, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :title, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :titleAlignment, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :titleBaseWritingDirection, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :titleFont, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :titleWidth, [{:args=>0, :names=>[], :types=>[], :retval=>"d"}, {:args=>1, :names=>[], :types=>["{CGSize=dd}"], :retval=>"d"}]
  end
end
