# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSFontDescriptor < Cocoa::NSObject
    attach_method :fontAttributes, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :fontDescriptorByAddingAttributes, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :fontDescriptorWithFace, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :fontDescriptorWithFamily, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :fontDescriptorWithFontAttributes, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :fontDescriptorWithMatrix, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :fontDescriptorWithName, [{:args=>2, :names=>[:matrix], :types=>["@", "@"], :retval=>"@"}, {:args=>2, :names=>[:size], :types=>["@", "d"], :retval=>"@"}]
    attach_method :fontDescriptorWithSize, :args=>1, :names=>[], :types=>["d"], :retval=>"@"
    attach_method :fontDescriptorWithSymbolicTraits, :args=>1, :names=>[], :types=>["I"], :retval=>"@"
    attach_method :initWithFontAttributes, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :matchingFontDescriptorWithMandatoryKeys, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :matchingFontDescriptorsWithMandatoryKeys, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :matrix, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :objectForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :pointSize, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :postscriptName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :symbolicTraits, :args=>0, :names=>[], :types=>[], :retval=>"I"
  end
end
