# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSHost < Cocoa::NSObject
    attach_method :address, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :addresses, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :currentHost, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :flushHostCache, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_singular_method :hostWithAddress, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :hostWithName, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :isEqualToHost, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_singular_method :isHostCacheEnabled, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :localizedName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :name, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :names, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :setHostCacheEnabled, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
  end
end
