# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSHTTPCookieStorage < Cocoa::NSObject
    attach_method :cookieAcceptPolicy, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :cookies, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :cookiesForURL, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :deleteCookie, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setCookie, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setCookieAcceptPolicy, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setCookies, :args=>3, :names=>[:forURL, :mainDocumentURL], :types=>["@", "@", "@"], :retval=>"v"
    attach_singular_method :sharedHTTPCookieStorage, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :sortedCookiesUsingDescriptors, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
  end
end
