# generated by 'rake generate'
require 'cocoa/bindings/NSCell'
module Cocoa
  class NSImageCell < Cocoa::NSCell
    attach_method :imageAlignment, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :imageFrameStyle, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :imageScaling, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :setImageAlignment, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setImageFrameStyle, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setImageScaling, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
  end
end
