# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSIndexPath < Cocoa::NSObject
    attach_method :compare, :args=>1, :names=>[], :types=>["@"], :retval=>"q"
    attach_method :getIndexes, :args=>1, :names=>[], :types=>["^Q"], :retval=>"v"
    attach_method :indexAtPosition, :args=>1, :names=>[], :types=>["Q"], :retval=>"Q"
    attach_method :indexPathByAddingIndex, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_method :indexPathByRemovingLastIndex, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :indexPathWithIndex, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_singular_method :indexPathWithIndexes, :args=>2, :names=>["length"], :types=>["^Q", "Q"], :retval=>"@"
    attach_method :initWithIndex, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_method :initWithIndexes, :args=>2, :names=>["length"], :types=>["^Q", "Q"], :retval=>"@"
    attach_method :length, :args=>0, :names=>[], :types=>[], :retval=>"Q"
  end
end
