# generated by 'rake generate'
require 'cocoa/bindings/NSPersistentStore'
module Cocoa
  class NSIncrementalStore < Cocoa::NSPersistentStore
    attach_method :executeRequest, :args=>3, :names=>[:withContext, :error], :types=>["@", "@", "^@"], :retval=>"@"
    attach_singular_method :identifierForNewStoreAtURL, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :loadMetadata, :args=>1, :names=>[], :types=>["^@"], :retval=>"B"
    attach_method :managedObjectContextDidRegisterObjectsWithIDs, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :managedObjectContextDidUnregisterObjectsWithIDs, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :newObjectIDForEntity, :args=>2, :names=>[:referenceObject], :types=>["@", "@"], :retval=>"@"
    attach_method :newValueForRelationship, :args=>4, :names=>[:forObjectWithID, :withContext, :error], :types=>["@", "@", "@", "^@"], :retval=>"@"
    attach_method :newValuesForObjectWithID, :args=>3, :names=>[:withContext, :error], :types=>["@", "@", "^@"], :retval=>"@"
    attach_method :obtainPermanentIDsForObjects, :args=>2, :names=>[:error], :types=>["@", "^@"], :retval=>"@"
    attach_method :referenceObjectForObjectID, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
  end
end
