# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSInvocation < Cocoa::NSObject
    attach_method :argumentsRetained, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :getArgument, :args=>2, :names=>[:atIndex], :types=>["^v", "q"], :retval=>"v"
    attach_method :getReturnValue, :args=>1, :names=>[], :types=>["^v"], :retval=>"v"
    attach_singular_method :invocationWithMethodSignature, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :invoke, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :invokeWithTarget, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :methodSignature, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :retainArguments, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :selector, :args=>0, :names=>[], :types=>[], :retval=>":"
    attach_method :setArgument, :args=>2, :names=>[:atIndex], :types=>["^v", "q"], :retval=>"v"
    attach_method :setReturnValue, :args=>1, :names=>[], :types=>["^v"], :retval=>"v"
    attach_method :setSelector, :args=>1, :names=>[], :types=>[":"], :retval=>"v"
    attach_method :setTarget, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :target, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
