# generated by 'rake generate'
require 'cocoa/bindings/NSCoder'
module Cocoa
  class NSKeyedArchiver < Cocoa::NSCoder
    attach_singular_method :archiveRootObject, :args=>2, :names=>["toFile"], :types=>["@", "@"], :retval=>"B"
    attach_singular_method :archivedDataWithRootObject, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :classNameForClass, :args=>1, :names=>[], :types=>["#"], :retval=>"@"
    attach_method :classNameForClass, :args=>1, :names=>[], :types=>["#"], :retval=>"@"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :encodeBool, :args=>2, :names=>["forKey"], :types=>["B", "@"], :retval=>"v"
    attach_method :encodeBytes, :args=>3, :names=>["length", "forKey"], :types=>["*", "Q", "@"], :retval=>"v"
    attach_method :encodeConditionalObject, :args=>2, :names=>["forKey"], :types=>["@", "@"], :retval=>"v"
    attach_method :encodeDouble, :args=>2, :names=>["forKey"], :types=>["d", "@"], :retval=>"v"
    attach_method :encodeFloat, :args=>2, :names=>["forKey"], :types=>["f", "@"], :retval=>"v"
    attach_method :encodeInt32, :args=>2, :names=>["forKey"], :types=>["i", "@"], :retval=>"v"
    attach_method :encodeInt64, :args=>2, :names=>["forKey"], :types=>["q", "@"], :retval=>"v"
    attach_method :encodeInt, :args=>2, :names=>["forKey"], :types=>["i", "@"], :retval=>"v"
    attach_method :encodeObject, :args=>2, :names=>["forKey"], :types=>["@", "@"], :retval=>"v"
    attach_method :finishEncoding, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :initForWritingWithMutableData, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :outputFormat, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_singular_method :setClassName, :args=>2, :names=>["forClass"], :types=>["@", "#"], :retval=>"v"
    attach_method :setClassName, :args=>2, :names=>["forClass"], :types=>["@", "#"], :retval=>"v"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setOutputFormat, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
  end
end
