# generated by 'rake generate'
require 'cocoa/bindings/NSControl'
module Cocoa
  class NSLevelIndicator < Cocoa::NSControl
    attach_method :criticalValue, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :maxValue, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :minValue, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :numberOfMajorTickMarks, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :numberOfTickMarks, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :rectOfTickMarkAtIndex, :args=>1, :names=>[], :types=>["q"], :retval=>"{CGRect={CGPoint=dd}{CGSize=dd}}"
    attach_method :setCriticalValue, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setMaxValue, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setMinValue, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setNumberOfMajorTickMarks, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setNumberOfTickMarks, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setTickMarkPosition, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setWarningValue, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :tickMarkPosition, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :tickMarkValueAtIndex, :args=>1, :names=>[], :types=>["q"], :retval=>"d"
    attach_method :warningValue, :args=>0, :names=>[], :types=>[], :retval=>"d"
  end
end
