# generated by 'rake generate'
require 'cocoa/bindings/NSScriptWhoseTest'
module Cocoa
  class NSLogicalTest < Cocoa::NSScriptWhoseTest
    attach_method :initAndTestWithTests, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :initNotTestWithTest, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :initOrTestWithTests, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
  end
end
