# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSManagedObjectModel < Cocoa::NSObject
    attach_method :configurations, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :entities, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :entitiesByName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :entitiesForConfiguration, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :entityVersionHashesByName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :fetchRequestFromTemplateWithName, :args=>2, :names=>[:substitutionVariables], :types=>["@", "@"], :retval=>"@"
    attach_method :fetchRequestTemplateForName, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :fetchRequestTemplatesByName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :init, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithContentsOfURL, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :isConfiguration, :args=>2, :names=>[:compatibleWithStoreMetadata], :types=>["@", "@"], :retval=>"B"
    attach_method :localizationDictionary, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :mergedModelFromBundles, [{:args=>1, :names=>[], :types=>["@"], :retval=>"@"}, {:args=>2, :names=>[:forStoreMetadata], :types=>["@", "@"], :retval=>"@"}]
    attach_singular_method :modelByMergingModels, [{:args=>1, :names=>[], :types=>["@"], :retval=>"@"}, {:args=>2, :names=>[:forStoreMetadata], :types=>["@", "@"], :retval=>"@"}]
    attach_method :setEntities, [{:args=>1, :names=>[], :types=>["@"], :retval=>"v"}, {:args=>2, :names=>[:forConfiguration], :types=>["@", "@"], :retval=>"v"}]
    attach_method :setFetchRequestTemplate, :args=>2, :names=>[:forName], :types=>["@", "@"], :retval=>"v"
    attach_method :setLocalizationDictionary, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setVersionIdentifiers, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :versionIdentifiers, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
