# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSMappingModel < Cocoa::NSObject
    attach_method :entityMappings, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :entityMappingsByName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :inferredMappingModelForSourceModel, :args=>3, :names=>[:destinationModel, :error], :types=>["@", "@", "^@"], :retval=>"@"
    attach_method :initWithContentsOfURL, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :mappingModelFromBundles, :args=>3, :names=>[:forSourceModel, :destinationModel], :types=>["@", "@", "@"], :retval=>"@"
    attach_method :setEntityMappings, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
