# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSManagedObjectID < Cocoa::NSObject
    attach_method :URIRepresentation, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :entity, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :isTemporaryID, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :persistentStore, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
