# generated by 'rake generate'
require 'cocoa/bindings/NSButtonCell'
module Cocoa
  class NSMenuItemCell < Cocoa::NSButtonCell
    attach_method :calcSize, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :drawBorderAndBackgroundWithFrame, :args=>2, :names=>[:inView], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}", "@"], :retval=>"v"
    attach_method :drawImageWithFrame, :args=>2, :names=>[:inView], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}", "@"], :retval=>"v"
    attach_method :drawKeyEquivalentWithFrame, :args=>2, :names=>[:inView], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}", "@"], :retval=>"v"
    attach_method :drawSeparatorItemWithFrame, :args=>2, :names=>[:inView], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}", "@"], :retval=>"v"
    attach_method :drawStateImageWithFrame, :args=>2, :names=>[:inView], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}", "@"], :retval=>"v"
    attach_method :drawTitleWithFrame, :args=>2, :names=>[:inView], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}", "@"], :retval=>"v"
    attach_method :imageWidth, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :keyEquivalentRectForBounds, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"{CGRect={CGPoint=dd}{CGSize=dd}}"
    attach_method :keyEquivalentWidth, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :menuItem, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :needsDisplay, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :needsSizing, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :setMenuItem, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setNeedsDisplay, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setNeedsSizing, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :stateImageRectForBounds, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"{CGRect={CGPoint=dd}{CGSize=dd}}"
    attach_method :stateImageWidth, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :tag, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :titleRectForBounds, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"{CGRect={CGPoint=dd}{CGSize=dd}}"
    attach_method :titleWidth, :args=>0, :names=>[], :types=>[], :retval=>"d"
  end
end
