# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSMethodSignature < Cocoa::NSObject
    attach_method :frameLength, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :getArgumentTypeAtIndex, :args=>1, :names=>[], :types=>["Q"], :retval=>"*"
    attach_method :isOneway, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :methodReturnLength, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :methodReturnType, :args=>0, :names=>[], :types=>[], :retval=>"*"
    attach_method :numberOfArguments, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_singular_method :signatureWithObjCTypes, :args=>1, :names=>[], :types=>["*"], :retval=>"@"
  end
end
