# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSMergeConflict < Cocoa::NSObject
    attach_method :cachedSnapshot, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithSource, :args=>5, :names=>[:newVersion, :oldVersion, :cachedSnapshot, :persistedSnapshot], :types=>["@", "Q", "Q", "@", "@"], :retval=>"@"
    attach_method :newVersionNumber, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :objectSnapshot, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :oldVersionNumber, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :persistedSnapshot, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :sourceObject, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
