# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSMetadataQueryAttributeValueTuple < Cocoa::NSObject
    attach_method :attribute, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :count, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :value, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
