# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSMergePolicy < Cocoa::NSObject
    attach_method :initWithMergeType, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_method :mergeType, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :resolveConflicts, :args=>2, :names=>[:error], :types=>["@", "^@"], :retval=>"B"
  end
end
