# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSMetadataQueryResultGroup < Cocoa::NSObject
    attach_method :attribute, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :resultAtIndex, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_method :resultCount, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :results, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :subgroups, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :value, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
