# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSMigrationManager < Cocoa::NSObject
    attach_method :associateSourceInstance, :args=>3, :names=>[:withDestinationInstance, :forEntityMapping], :types=>["@", "@", "@"], :retval=>"v"
    attach_method :cancelMigrationWithError, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :currentEntityMapping, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :destinationContext, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :destinationEntityForEntityMapping, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :destinationInstancesForEntityMappingNamed, :args=>2, :names=>[:sourceInstances], :types=>["@", "@"], :retval=>"@"
    attach_method :destinationModel, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithSourceModel, :args=>2, :names=>[:destinationModel], :types=>["@", "@"], :retval=>"@"
    attach_method :mappingModel, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :migrateStoreFromURL, :args=>8, :names=>[:type, :options, :withMappingModel, :toDestinationURL, :destinationType, :destinationOptions, :error], :types=>["@", "@", "@", "@", "@", "@", "@", "^@"], :retval=>"B"
    attach_method :migrationProgress, :args=>0, :names=>[], :types=>[], :retval=>"f"
    attach_method :reset, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :setUserInfo, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setUsesStoreSpecificMigrationManager, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :sourceContext, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :sourceEntityForEntityMapping, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :sourceInstancesForEntityMappingNamed, :args=>2, :names=>[:destinationInstances], :types=>["@", "@"], :retval=>"@"
    attach_method :sourceModel, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :userInfo, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :usesStoreSpecificMigrationManager, :args=>0, :names=>[], :types=>[], :retval=>"B"
  end
end
