# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSMovie < Cocoa::NSObject
    attach_method :QTMovie, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithMovie, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
  end
end
