# generated by 'rake generate'
require 'cocoa/bindings/NSOrderedSet'
module Cocoa
  class NSMutableOrderedSet < Cocoa::NSOrderedSet
    attach_method :addObject, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :addObjects, :args=>2, :names=>[:count], :types=>["^@", "Q"], :retval=>"v"
    attach_method :addObjectsFromArray, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :exchangeObjectAtIndex, :args=>2, :names=>[:withObjectAtIndex], :types=>["Q", "Q"], :retval=>"v"
    attach_method :initWithCapacity, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_method :insertObject, :args=>2, :names=>[:atIndex], :types=>["@", "Q"], :retval=>"v"
    attach_method :insertObjects, :args=>2, :names=>[:atIndexes], :types=>["@", "@"], :retval=>"v"
    attach_method :intersectOrderedSet, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :intersectSet, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :minusOrderedSet, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :minusSet, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :moveObjectsAtIndexes, :args=>2, :names=>[:toIndex], :types=>["@", "Q"], :retval=>"v"
    attach_singular_method :orderedSetWithCapacity, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_method :removeAllObjects, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :removeObject, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :removeObjectAtIndex, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :removeObjectsAtIndexes, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :removeObjectsInArray, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :removeObjectsInRange, :args=>1, :names=>[], :types=>["{_NSRange=QQ}"], :retval=>"v"
    attach_method :replaceObjectAtIndex, :args=>2, :names=>[:withObject], :types=>["Q", "@"], :retval=>"v"
    attach_method :replaceObjectsAtIndexes, :args=>2, :names=>[:withObjects], :types=>["@", "@"], :retval=>"v"
    attach_method :replaceObjectsInRange, :args=>3, :names=>[:withObjects, :count], :types=>["{_NSRange=QQ}", "^@", "Q"], :retval=>"v"
    attach_method :setObject, [{:args=>2, :names=>[:atIndex], :types=>["@", "Q"], :retval=>"v"}, {:args=>2, :names=>[:atIndexedSubscript], :types=>["@", "Q"], :retval=>"v"}]
    attach_method :sortRange, :args=>3, :names=>[:options, :usingComparator], :types=>["{_NSRange=QQ}", "Q", "@?"], :retval=>"v"
    attach_method :sortUsingComparator, :args=>1, :names=>[], :types=>["@?"], :retval=>"v"
    attach_method :sortWithOptions, :args=>2, :names=>[:usingComparator], :types=>["Q", "@?"], :retval=>"v"
    attach_method :unionOrderedSet, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :unionSet, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
