# generated by 'rake generate'
require 'cocoa/bindings/NSSet'
module Cocoa
  class NSMutableSet < Cocoa::NSSet
    attach_method :addObject, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :addObjectsFromArray, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :filterUsingPredicate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :initWithCapacity, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_method :intersectSet, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :minusSet, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :removeAllObjects, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :removeObject, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setSet, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_singular_method :setWithCapacity, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_method :unionSet, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
