# generated by 'rake generate'
require 'cocoa/bindings/NSArray'
module Cocoa
  class NSMutableArray < Cocoa::NSArray
    attach_method :addObject, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :addObjectsFromArray, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_singular_method :arrayWithCapacity, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_method :exchangeObjectAtIndex, :args=>2, :names=>[:withObjectAtIndex], :types=>["Q", "Q"], :retval=>"v"
    attach_method :filterUsingPredicate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :initWithCapacity, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_method :insertObject, :args=>2, :names=>[:atIndex], :types=>["@", "Q"], :retval=>"v"
    attach_method :insertObjects, :args=>2, :names=>[:atIndexes], :types=>["@", "@"], :retval=>"v"
    attach_method :removeAllObjects, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :removeLastObject, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :removeObject, [{:args=>1, :names=>[], :types=>["@"], :retval=>"v"}, {:args=>2, :names=>[:inRange], :types=>["@", "{_NSRange=QQ}"], :retval=>"v"}]
    attach_method :removeObjectAtIndex, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :removeObjectIdenticalTo, [{:args=>1, :names=>[], :types=>["@"], :retval=>"v"}, {:args=>2, :names=>[:inRange], :types=>["@", "{_NSRange=QQ}"], :retval=>"v"}]
    attach_method :removeObjectsAtIndexes, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :removeObjectsFromIndices, :args=>2, :names=>[:numIndices], :types=>["^Q", "Q"], :retval=>"v"
    attach_method :removeObjectsInArray, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :removeObjectsInRange, :args=>1, :names=>[], :types=>["{_NSRange=QQ}"], :retval=>"v"
    attach_method :replaceObjectAtIndex, :args=>2, :names=>[:withObject], :types=>["Q", "@"], :retval=>"v"
    attach_method :replaceObjectsAtIndexes, :args=>2, :names=>[:withObjects], :types=>["@", "@"], :retval=>"v"
    attach_method :replaceObjectsInRange, [{:args=>2, :names=>[:withObjectsFromArray], :types=>["{_NSRange=QQ}", "@"], :retval=>"v"}, {:args=>3, :names=>[:withObjectsFromArray, :range], :types=>["{_NSRange=QQ}", "@", "{_NSRange=QQ}"], :retval=>"v"}]
    attach_method :setArray, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setObject, :args=>2, :names=>[:atIndexedSubscript], :types=>["@", "Q"], :retval=>"v"
    attach_method :sortUsingComparator, :args=>1, :names=>[], :types=>["@?"], :retval=>"v"
    attach_method :sortUsingDescriptors, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :sortUsingFunction, :args=>2, :names=>[:context], :types=>["^?", "^v"], :retval=>"v"
    attach_method :sortUsingSelector, :args=>1, :names=>[], :types=>[":"], :retval=>"v"
    attach_method :sortWithOptions, :args=>2, :names=>[:usingComparator], :types=>["Q", "@?"], :retval=>"v"
  end
end
