# generated by 'rake generate'
require 'cocoa/bindings/NSDictionary'
module Cocoa
  class NSMutableDictionary < Cocoa::NSDictionary
    attach_method :addEntriesFromDictionary, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_singular_method :dictionaryWithCapacity, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_singular_method :dictionaryWithSharedKeySet, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :initWithCapacity, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_method :removeAllObjects, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :removeObjectForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :removeObjectsForKeys, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDictionary, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setObject, [{:args=>2, :names=>["forKey"], :types=>["@", "@"], :retval=>"v"}, {:args=>2, :names=>["forKeyedSubscript"], :types=>["@", "@"], :retval=>"v"}]
    attach_method :setValue, :args=>2, :names=>["forKey"], :types=>["@", "@"], :retval=>"v"
  end
end
