# generated by 'rake generate'
require 'cocoa/bindings/NSURLRequest'
module Cocoa
  class NSMutableURLRequest < Cocoa::NSURLRequest
    attach_method :addValue, :args=>2, :names=>["forHTTPHeaderField"], :types=>["@", "@"], :retval=>"v"
    attach_method :setAllHTTPHeaderFields, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setAllowsCellularAccess, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setCachePolicy, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setHTTPBody, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setHTTPBodyStream, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setHTTPMethod, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setHTTPShouldHandleCookies, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setHTTPShouldUsePipelining, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setMainDocumentURL, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setNetworkServiceType, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setTimeoutInterval, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setURL, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setValue, :args=>2, :names=>["forHTTPHeaderField"], :types=>["@", "@"], :retval=>"v"
  end
end
