# generated by 'rake generate'
require 'cocoa/bindings/NSFontCollection'
module Cocoa
  class NSMutableFontCollection < Cocoa::NSFontCollection
    attach_method :addQueryForDescriptors, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :removeQueryForDescriptors, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setExclusionDescriptors, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setQueryDescriptors, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
