# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSNib < Cocoa::NSObject
    attach_method :initWithContentsOfURL, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :initWithNibData, :args=>2, :names=>[:bundle], :types=>["@", "@"], :retval=>"@"
    attach_method :initWithNibNamed, :args=>2, :names=>[:bundle], :types=>["@", "@"], :retval=>"@"
    attach_method :instantiateNibWithExternalNameTable, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :instantiateNibWithOwner, :args=>2, :names=>[:topLevelObjects], :types=>["@", "^@"], :retval=>"B"
    attach_method :instantiateWithOwner, :args=>2, :names=>[:topLevelObjects], :types=>["@", "^@"], :retval=>"B"
  end
end
