# generated by 'rake generate'
require 'cocoa/bindings/NSNibConnector'
module Cocoa
  class NSNibOutletConnector < Cocoa::NSNibConnector
    attach_method :establishConnection, :args=>0, :names=>[], :types=>[], :retval=>"v"
  end
end
