# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSNotificationQueue < Cocoa::NSObject
    attach_singular_method :defaultQueue, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :dequeueNotificationsMatching, :args=>2, :names=>[:coalesceMask], :types=>["@", "Q"], :retval=>"v"
    attach_method :enqueueNotification, [{:args=>2, :names=>[:postingStyle], :types=>["@", "Q"], :retval=>"v"}, {:args=>4, :names=>[:postingStyle, :coalesceMask, :forModes], :types=>["@", "Q", "Q", "@"], :retval=>"v"}]
    attach_method :initWithNotificationCenter, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
  end
end
