# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSNull < Cocoa::NSObject
    attach_singular_method :null, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
