# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSOpenGLPixelFormat < Cocoa::NSObject
    attach_method :CGLPixelFormatObj, :args=>0, :names=>[], :types=>[], :retval=>"^v"
    attach_method :attributes, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :getValues, :args=>3, :names=>[:forAttribute, :forVirtualScreen], :types=>["^i", "I", "i"], :retval=>"v"
    attach_method :initWithAttributes, :args=>1, :names=>[], :types=>["^I"], :retval=>"@"
    attach_method :initWithCGLPixelFormatObj, :args=>1, :names=>[], :types=>["^v"], :retval=>"@"
    attach_method :initWithData, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :numberOfVirtualScreens, :args=>0, :names=>[], :types=>[], :retval=>"i"
    attach_method :setAttributes, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
