# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSOperationQueue < Cocoa::NSObject
    attach_method :addOperation, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :addOperationWithBlock, :args=>1, :names=>[], :types=>["@?"], :retval=>"v"
    attach_method :addOperations, :args=>2, :names=>[:waitUntilFinished], :types=>["@", "B"], :retval=>"v"
    attach_method :cancelAllOperations, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_singular_method :currentQueue, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :isSuspended, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_singular_method :mainQueue, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :maxConcurrentOperationCount, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :name, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :operationCount, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :operations, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setMaxConcurrentOperationCount, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setSuspended, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :waitUntilAllOperationsAreFinished, :args=>0, :names=>[], :types=>[], :retval=>"v"
  end
end
