# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSOperation < Cocoa::NSObject
    attach_method :addDependency, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :cancel, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :completionBlock, :args=>0, :names=>[], :types=>[], :retval=>"@?"
    attach_method :dependencies, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :init, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :isCancelled, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isConcurrent, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isExecuting, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isFinished, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isReady, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :main, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :queuePriority, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :removeDependency, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setCompletionBlock, :args=>1, :names=>[], :types=>["@?"], :retval=>"v"
    attach_method :setQueuePriority, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setThreadPriority, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :start, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :threadPriority, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :waitUntilFinished, :args=>0, :names=>[], :types=>[], :retval=>"v"
  end
end
