# generated by 'rake generate'
require 'cocoa/bindings/NSTableView'
module Cocoa
  class NSOutlineView < Cocoa::NSTableView
    attach_method :autoresizesOutlineColumn, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :autosaveExpandedItems, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :collapseItem, [{:args=>1, :names=>[], :types=>["@"], :retval=>"v"}, {:args=>2, :names=>["collapseChildren"], :types=>["@", "B"], :retval=>"v"}]
    attach_method :dataSource, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :expandItem, [{:args=>1, :names=>[], :types=>["@"], :retval=>"v"}, {:args=>2, :names=>["expandChildren"], :types=>["@", "B"], :retval=>"v"}]
    attach_method :frameOfOutlineCellAtRow, :args=>1, :names=>[], :types=>["q"], :retval=>"{CGRect={CGPoint=dd}{CGSize=dd}}"
    attach_method :indentationMarkerFollowsCell, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :indentationPerLevel, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :insertItemsAtIndexes, :args=>3, :names=>["inParent", "withAnimation"], :types=>["@", "@", "Q"], :retval=>"v"
    attach_method :isExpandable, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :isItemExpanded, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :itemAtRow, :args=>1, :names=>[], :types=>["q"], :retval=>"@"
    attach_method :levelForItem, :args=>1, :names=>[], :types=>["@"], :retval=>"q"
    attach_method :levelForRow, :args=>1, :names=>[], :types=>["q"], :retval=>"q"
    attach_method :moveItemAtIndex, :args=>4, :names=>["inParent", "toIndex", "inParent"], :types=>["q", "@", "q", "@"], :retval=>"v"
    attach_method :outlineTableColumn, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :parentForItem, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :reloadItem, [{:args=>1, :names=>[], :types=>["@"], :retval=>"v"}, {:args=>2, :names=>["reloadChildren"], :types=>["@", "B"], :retval=>"v"}]
    attach_method :removeItemsAtIndexes, :args=>3, :names=>["inParent", "withAnimation"], :types=>["@", "@", "Q"], :retval=>"v"
    attach_method :rowForItem, :args=>1, :names=>[], :types=>["@"], :retval=>"q"
    attach_method :setAutoresizesOutlineColumn, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setAutosaveExpandedItems, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setDataSource, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDropItem, :args=>2, :names=>["dropChildIndex"], :types=>["@", "q"], :retval=>"v"
    attach_method :setIndentationMarkerFollowsCell, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setIndentationPerLevel, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setOutlineTableColumn, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :shouldCollapseAutoExpandedItemsForDeposited, :args=>1, :names=>[], :types=>["B"], :retval=>"B"
  end
end
