# generated by 'rake generate'
require 'cocoa/bindings/NSControl'
module Cocoa
  class NSPathControl < Cocoa::NSControl
    attach_method :URL, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :backgroundColor, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :clickedPathComponentCell, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :doubleAction, :args=>0, :names=>[], :types=>[], :retval=>":"
    attach_method :menu, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :pathComponentCells, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :pathStyle, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :setBackgroundColor, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDoubleAction, :args=>1, :names=>[], :types=>[":"], :retval=>"v"
    attach_method :setDraggingSourceOperationMask, :args=>2, :names=>[:forLocal], :types=>["Q", "B"], :retval=>"v"
    attach_method :setMenu, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setPathComponentCells, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setPathStyle, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setURL, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
