# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSPasteboardItem < Cocoa::NSObject
    attach_method :availableTypeFromArray, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :dataForType, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :propertyListForType, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :setData, :args=>2, :names=>["forType"], :types=>["@", "@"], :retval=>"B"
    attach_method :setDataProvider, :args=>2, :names=>["forTypes"], :types=>["@", "@"], :retval=>"B"
    attach_method :setPropertyList, :args=>2, :names=>["forType"], :types=>["@", "@"], :retval=>"B"
    attach_method :setString, :args=>2, :names=>["forType"], :types=>["@", "@"], :retval=>"B"
    attach_method :stringForType, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :types, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
