# generated by 'rake generate'
require 'cocoa/bindings/NSWindow'
module Cocoa
  class NSPanel < Cocoa::NSWindow
    attach_method :becomesKeyOnlyIfNeeded, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isFloatingPanel, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :setBecomesKeyOnlyIfNeeded, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setFloatingPanel, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setWorksWhenModal, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :worksWhenModal, :args=>0, :names=>[], :types=>[], :retval=>"B"
  end
end
