# generated by 'rake generate'
require 'cocoa/bindings/NSActionCell'
module Cocoa
  class NSPathCell < Cocoa::NSActionCell
    attach_method :URL, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :allowedTypes, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :backgroundColor, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :clickedPathComponentCell, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :doubleAction, :args=>0, :names=>[], :types=>[], :retval=>":"
    attach_method :mouseEntered, :args=>3, :names=>[:withFrame, :inView], :types=>["@", "{CGRect={CGPoint=dd}{CGSize=dd}}", "@"], :retval=>"v"
    attach_method :mouseExited, :args=>3, :names=>[:withFrame, :inView], :types=>["@", "{CGRect={CGPoint=dd}{CGSize=dd}}", "@"], :retval=>"v"
    attach_method :pathComponentCellAtPoint, :args=>3, :names=>[:withFrame, :inView], :types=>["{CGPoint=dd}", "{CGRect={CGPoint=dd}{CGSize=dd}}", "@"], :retval=>"@"
    attach_singular_method :pathComponentCellClass, :args=>0, :names=>[], :types=>[], :retval=>"#"
    attach_method :pathComponentCells, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :pathStyle, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :placeholderAttributedString, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :placeholderString, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :rectOfPathComponentCell, :args=>3, :names=>[:withFrame, :inView], :types=>["@", "{CGRect={CGPoint=dd}{CGSize=dd}}", "@"], :retval=>"{CGRect={CGPoint=dd}{CGSize=dd}}"
    attach_method :setAllowedTypes, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setBackgroundColor, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setControlSize, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDoubleAction, :args=>1, :names=>[], :types=>[":"], :retval=>"v"
    attach_method :setObjectValue, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setPathComponentCells, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setPathStyle, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setPlaceholderAttributedString, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setPlaceholderString, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setURL, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
