# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSParagraphStyle < Cocoa::NSObject
    attach_method :alignment, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :baseWritingDirection, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_singular_method :defaultParagraphStyle, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :defaultTabInterval, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_singular_method :defaultWritingDirectionForLanguage, :args=>1, :names=>[], :types=>["@"], :retval=>"q"
    attach_method :firstLineHeadIndent, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :headIndent, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :headerLevel, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :hyphenationFactor, :args=>0, :names=>[], :types=>[], :retval=>"f"
    attach_method :lineBreakMode, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :lineHeightMultiple, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :lineSpacing, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :maximumLineHeight, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :minimumLineHeight, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :paragraphSpacing, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :paragraphSpacingBefore, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :tabStops, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :tailIndent, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :textBlocks, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :textLists, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :tighteningFactorForTruncation, :args=>0, :names=>[], :types=>[], :retval=>"f"
  end
end
