# generated by 'rake generate'
require 'cocoa/bindings/NSTextFieldCell'
module Cocoa
  class NSPathComponentCell < Cocoa::NSTextFieldCell
    attach_method :URL, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :image, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setImage, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setURL, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
