# generated by 'rake generate'
require 'cocoa/bindings/NSViewController'
module Cocoa
  class NSPageController < Cocoa::NSViewController
    attach_method :arrangedObjects, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :completeTransition, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :navigateBack, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :navigateForward, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :navigateForwardToObject, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :selectedIndex, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :selectedViewController, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setArrangedObjects, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setSelectedIndex, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setTransitionStyle, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :takeSelectedIndexFrom, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :transitionStyle, :args=>0, :names=>[], :types=>[], :retval=>"q"
  end
end
