# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSPersistentStore < Cocoa::NSObject
    attach_method :URL, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :configurationName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :didAddToPersistentStoreCoordinator, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :identifier, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithPersistentStoreCoordinator, :args=>4, :names=>[:configurationName, :URL, :options], :types=>["@", "@", "@", "@"], :retval=>"@"
    attach_method :isReadOnly, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :loadMetadata, :args=>1, :names=>[], :types=>["^@"], :retval=>"B"
    attach_method :metadata, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :metadataForPersistentStoreWithURL, :args=>2, :names=>[:error], :types=>["@", "^@"], :retval=>"@"
    attach_singular_method :migrationManagerClass, :args=>0, :names=>[], :types=>[], :retval=>"#"
    attach_method :options, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :persistentStoreCoordinator, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setIdentifier, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setMetadata, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_singular_method :setMetadata, :args=>3, :names=>[:forPersistentStoreWithURL, :error], :types=>["@", "@", "^@"], :retval=>"B"
    attach_method :setReadOnly, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setURL, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :type, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :willRemoveFromPersistentStoreCoordinator, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
