# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSPersistentStoreRequest < Cocoa::NSObject
    attach_method :affectedStores, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :requestType, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :setAffectedStores, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
