# generated by 'rake generate'
require 'cocoa/bindings/NSDocument'
module Cocoa
  class NSPersistentDocument < Cocoa::NSDocument
    attach_method :configurePersistentStoreCoordinatorForURL, [{:args=>3, :names=>["ofType", "error"], :types=>["@", "@", "^@"], :retval=>"B"}, {:args=>5, :names=>["ofType", "modelConfiguration", "storeOptions", "error"], :types=>["@", "@", "@", "@", "^@"], :retval=>"B"}]
    attach_method :managedObjectContext, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :managedObjectModel, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :persistentStoreTypeForFileType, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :readFromURL, :args=>3, :names=>["ofType", "error"], :types=>["@", "@", "^@"], :retval=>"B"
    attach_method :revertToContentsOfURL, :args=>3, :names=>["ofType", "error"], :types=>["@", "@", "^@"], :retval=>"B"
    attach_method :setManagedObjectContext, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :writeToURL, :args=>5, :names=>["ofType", "forSaveOperation", "originalContentsURL", "error"], :types=>["@", "@", "Q", "@", "^@"], :retval=>"B"
  end
end
