# generated by 'rake generate'
require 'cocoa/bindings/NSImageRep'
module Cocoa
  class NSPICTImageRep < Cocoa::NSImageRep
    attach_method :PICTRepresentation, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :boundingBox, :args=>0, :names=>[], :types=>[], :retval=>"{CGRect={CGPoint=dd}{CGSize=dd}}"
    attach_singular_method :imageRepWithData, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :initWithData, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
  end
end
