# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSPointerArray < Cocoa::NSObject
    attach_method :addPointer, :args=>1, :names=>[], :types=>["^v"], :retval=>"v"
    attach_method :allObjects, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :compact, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :count, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :initWithOptions, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_method :initWithPointerFunctions, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :insertPointer, :args=>2, :names=>[:atIndex], :types=>["^v", "Q"], :retval=>"v"
    attach_singular_method :pointerArrayWithOptions, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_singular_method :pointerArrayWithPointerFunctions, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :pointerArrayWithStrongObjects, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :pointerArrayWithWeakObjects, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :pointerAtIndex, :args=>1, :names=>[], :types=>["Q"], :retval=>"^v"
    attach_method :pointerFunctions, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :removePointerAtIndex, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :replacePointerAtIndex, :args=>2, :names=>[:withPointer], :types=>["Q", "^v"], :retval=>"v"
    attach_method :setCount, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_singular_method :strongObjectsPointerArray, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :weakObjectsPointerArray, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
