# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSPort < Cocoa::NSObject
    attach_method :addConnection, :args=>3, :names=>["toRunLoop", "forMode"], :types=>["@", "@", "@"], :retval=>"v"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :invalidate, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :isValid, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_singular_method :port, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :removeConnection, :args=>3, :names=>["fromRunLoop", "forMode"], :types=>["@", "@", "@"], :retval=>"v"
    attach_method :removeFromRunLoop, :args=>2, :names=>["forMode"], :types=>["@", "@"], :retval=>"v"
    attach_method :reservedSpaceLength, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :scheduleInRunLoop, :args=>2, :names=>["forMode"], :types=>["@", "@"], :retval=>"v"
    attach_method :sendBeforeDate, [{:args=>4, :names=>["components", "from", "reserved"], :types=>["@", "@", "@", "Q"], :retval=>"B"}, {:args=>5, :names=>["msgid", "components", "from", "reserved"], :types=>["@", "Q", "@", "@", "Q"], :retval=>"B"}]
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
