# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSPortMessage < Cocoa::NSObject
    attach_method :components, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithSendPort, :args=>3, :names=>[:receivePort, :components], :types=>["@", "@", "@"], :retval=>"@"
    attach_method :msgid, :args=>0, :names=>[], :types=>[], :retval=>"I"
    attach_method :receivePort, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :sendBeforeDate, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :sendPort, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setMsgid, :args=>1, :names=>[], :types=>["I"], :retval=>"v"
  end
end
