# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSPortNameServer < Cocoa::NSObject
    attach_method :portForName, [{:args=>1, :names=>[], :types=>["@"], :retval=>"@"}, {:args=>2, :names=>["host"], :types=>["@", "@"], :retval=>"@"}]
    attach_method :registerPort, :args=>2, :names=>["name"], :types=>["@", "@"], :retval=>"B"
    attach_method :removePortForName, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_singular_method :systemDefaultPortNameServer, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
