# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSPointerFunctions < Cocoa::NSObject
    attach_method :acquireFunction, :args=>0, :names=>[], :types=>[], :retval=>"^?"
    attach_method :descriptionFunction, :args=>0, :names=>[], :types=>[], :retval=>"^?"
    attach_method :hashFunction, :args=>0, :names=>[], :types=>[], :retval=>"^?"
    attach_method :initWithOptions, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_method :isEqualFunction, :args=>0, :names=>[], :types=>[], :retval=>"^?"
    attach_singular_method :pointerFunctionsWithOptions, :args=>1, :names=>[], :types=>["Q"], :retval=>"@"
    attach_method :relinquishFunction, :args=>0, :names=>[], :types=>[], :retval=>"^?"
    attach_method :setAcquireFunction, :args=>1, :names=>[], :types=>["^?"], :retval=>"v"
    attach_method :setDescriptionFunction, :args=>1, :names=>[], :types=>["^?"], :retval=>"v"
    attach_method :setHashFunction, :args=>1, :names=>[], :types=>["^?"], :retval=>"v"
    attach_method :setIsEqualFunction, :args=>1, :names=>[], :types=>["^?"], :retval=>"v"
    attach_method :setRelinquishFunction, :args=>1, :names=>[], :types=>["^?"], :retval=>"v"
    attach_method :setSizeFunction, :args=>1, :names=>[], :types=>["^?"], :retval=>"v"
    attach_method :setUsesStrongWriteBarrier, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setUsesWeakReadAndWriteBarriers, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :sizeFunction, :args=>0, :names=>[], :types=>[], :retval=>"^?"
    attach_method :usesStrongWriteBarrier, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :usesWeakReadAndWriteBarriers, :args=>0, :names=>[], :types=>[], :retval=>"B"
  end
end
