# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSPropertyDescription < Cocoa::NSObject
    attach_method :entity, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :isIndexed, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isIndexedBySpotlight, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isOptional, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isStoredInExternalRecord, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isTransient, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :name, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :renamingIdentifier, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setIndexed, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setIndexedBySpotlight, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setOptional, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setRenamingIdentifier, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setStoredInExternalRecord, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setTransient, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setUserInfo, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setValidationPredicates, :args=>2, :names=>[:withValidationWarnings], :types=>["@", "@"], :retval=>"v"
    attach_method :setVersionHashModifier, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :userInfo, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :validationPredicates, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :validationWarnings, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :versionHash, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :versionHashModifier, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
