# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSPrintPanel < Cocoa::NSObject
    attach_method :accessoryControllers, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :accessoryView, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :addAccessoryController, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :beginSheetWithPrintInfo, :args=>5, :names=>[:modalForWindow, :delegate, :didEndSelector, :contextInfo], :types=>["@", "@", "@", ":", "^v"], :retval=>"v"
    attach_method :defaultButtonTitle, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :finalWritePrintInfo, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :helpAnchor, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :jobStyleHint, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :options, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :printInfo, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :printPanel, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :removeAccessoryController, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :runModal, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :runModalWithPrintInfo, :args=>1, :names=>[], :types=>["@"], :retval=>"q"
    attach_method :setAccessoryView, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDefaultButtonTitle, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setHelpAnchor, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setJobStyleHint, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setOptions, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :updateFromPrintInfo, :args=>0, :names=>[], :types=>[], :retval=>"v"
  end
end
