# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSPropertyMapping < Cocoa::NSObject
    attach_method :name, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setUserInfo, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setValueExpression, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :userInfo, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :valueExpression, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
