# generated by 'rake generate'
require 'cocoa/bindings/NSRuleEditor'
module Cocoa
  class NSPredicateEditor < Cocoa::NSRuleEditor
    attach_method :rowTemplates, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setRowTemplates, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
