# generated by 'rake generate'
require 'cocoa/bindings/NSView'
module Cocoa
  class NSProgressIndicator < Cocoa::NSView
    attach_method :animate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :animationDelay, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :controlSize, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :controlTint, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :doubleValue, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :incrementBy, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :isBezeled, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isDisplayedWhenStopped, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isIndeterminate, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :maxValue, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :minValue, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :setAnimationDelay, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setBezeled, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setControlSize, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setControlTint, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setDisplayedWhenStopped, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setDoubleValue, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setIndeterminate, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setMaxValue, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setMinValue, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setStyle, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setUsesThreadedAnimation, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :sizeToFit, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :startAnimation, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :stopAnimation, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :style, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :usesThreadedAnimation, :args=>0, :names=>[], :types=>[], :retval=>"B"
  end
end
