# generated by 'rake generate'
module Cocoa
  class NSProxy
    include Cocoa
    attach_singular_method :alloc, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :allocWithZone, :args=>1, :names=>[], :types=>["^{_NSZone=}"], :retval=>"@"
    attach_singular_method :class, :args=>0, :names=>[], :types=>[], :retval=>"#"
    attach_method :dealloc, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :debugDescription, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :description, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :finalize, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :forwardInvocation, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :methodSignatureForSelector, :args=>1, :names=>[], :types=>[":"], :retval=>"@"
    attach_singular_method :respondsToSelector, :args=>1, :names=>[], :types=>[":"], :retval=>"B"
  end
end
