# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSPropertyListSerialization < Cocoa::NSObject
    attach_singular_method :dataFromPropertyList, :args=>3, :names=>["format", "errorDescription"], :types=>["@", "Q", "^@"], :retval=>"@"
    attach_singular_method :dataWithPropertyList, :args=>4, :names=>["format", "options", "error"], :types=>["@", "Q", "Q", "^@"], :retval=>"@"
    attach_singular_method :propertyList, :args=>2, :names=>["isValidForFormat"], :types=>["@", "Q"], :retval=>"B"
    attach_singular_method :propertyListFromData, :args=>4, :names=>["mutabilityOption", "format", "errorDescription"], :types=>["@", "Q", "^Q", "^@"], :retval=>"@"
    attach_singular_method :propertyListWithData, :args=>4, :names=>["options", "format", "error"], :types=>["@", "Q", "^Q", "^@"], :retval=>"@"
    attach_singular_method :propertyListWithStream, :args=>4, :names=>["options", "format", "error"], :types=>["@", "Q", "^Q", "^@"], :retval=>"@"
    attach_singular_method :writePropertyList, :args=>5, :names=>["toStream", "format", "options", "error"], :types=>["@", "@", "Q", "Q", "^@"], :retval=>"q"
  end
end
