# generated by 'rake generate'
require 'cocoa/bindings/NSPropertyDescription'
module Cocoa
  class NSRelationshipDescription < Cocoa::NSPropertyDescription
    attach_method :deleteRule, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :destinationEntity, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :inverseRelationship, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :isOrdered, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isToMany, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :maxCount, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :minCount, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :setDeleteRule, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setDestinationEntity, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setInverseRelationship, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setMaxCount, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setMinCount, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setOrdered, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :versionHash, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
