# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSRunLoop < Cocoa::NSObject
    attach_method :acceptInputForMode, :args=>2, :names=>["beforeDate"], :types=>["@", "@"], :retval=>"v"
    attach_method :addPort, :args=>2, :names=>["forMode"], :types=>["@", "@"], :retval=>"v"
    attach_method :addTimer, :args=>2, :names=>["forMode"], :types=>["@", "@"], :retval=>"v"
    attach_method :cancelPerformSelector, :args=>3, :names=>["target", "argument"], :types=>[":", "@", "@"], :retval=>"v"
    attach_method :cancelPerformSelectorsWithTarget, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :configureAsServer, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :currentMode, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :currentRunLoop, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :getCFRunLoop, :args=>0, :names=>[], :types=>[], :retval=>"^{__CFRunLoop=}"
    attach_method :limitDateForMode, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :mainRunLoop, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :performSelector, :args=>5, :names=>["target", "argument", "order", "modes"], :types=>[":", "@", "@", "Q", "@"], :retval=>"v"
    attach_method :removePort, :args=>2, :names=>["forMode"], :types=>["@", "@"], :retval=>"v"
    attach_method :run, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :runMode, :args=>2, :names=>["beforeDate"], :types=>["@", "@"], :retval=>"B"
    attach_method :runUntilDate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
