# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSScanner < Cocoa::NSObject
    attach_method :caseSensitive, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :charactersToBeSkipped, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithString, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :isAtEnd, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :locale, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :localizedScannerWithString, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :scanCharactersFromSet, :args=>2, :names=>[:intoString], :types=>["@", "^@"], :retval=>"B"
    attach_method :scanDecimal, :args=>1, :names=>[], :types=>["^{_NSDecimal=b8b4b1b1b18[8S]}"], :retval=>"B"
    attach_method :scanDouble, :args=>1, :names=>[], :types=>["^d"], :retval=>"B"
    attach_method :scanFloat, :args=>1, :names=>[], :types=>["^f"], :retval=>"B"
    attach_method :scanHexDouble, :args=>1, :names=>[], :types=>["^d"], :retval=>"B"
    attach_method :scanHexFloat, :args=>1, :names=>[], :types=>["^f"], :retval=>"B"
    attach_method :scanHexInt, :args=>1, :names=>[], :types=>["^I"], :retval=>"B"
    attach_method :scanHexLongLong, :args=>1, :names=>[], :types=>["^Q"], :retval=>"B"
    attach_method :scanInt, :args=>1, :names=>[], :types=>["^i"], :retval=>"B"
    attach_method :scanInteger, :args=>1, :names=>[], :types=>["^q"], :retval=>"B"
    attach_method :scanLocation, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :scanLongLong, :args=>1, :names=>[], :types=>["^q"], :retval=>"B"
    attach_method :scanString, :args=>2, :names=>[:intoString], :types=>["@", "^@"], :retval=>"B"
    attach_method :scanUpToCharactersFromSet, :args=>2, :names=>[:intoString], :types=>["@", "^@"], :retval=>"B"
    attach_method :scanUpToString, :args=>2, :names=>[:intoString], :types=>["@", "^@"], :retval=>"B"
    attach_singular_method :scannerWithString, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :setCaseSensitive, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setCharactersToBeSkipped, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setLocale, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setScanLocation, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :string, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
