# generated by 'rake generate'
require 'cocoa/bindings/NSClassDescription'
module Cocoa
  class NSScriptClassDescription < Cocoa::NSClassDescription
    attach_method :appleEventCode, :args=>0, :names=>[], :types=>[], :retval=>"I"
    attach_method :appleEventCodeForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"I"
    attach_singular_method :classDescriptionForClass, :args=>1, :names=>[], :types=>["#"], :retval=>"@"
    attach_method :classDescriptionForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :className, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :defaultSubcontainerAttributeKey, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :hasOrderedToManyRelationshipForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :hasPropertyForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :hasReadablePropertyForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :hasWritablePropertyForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :implementationClassName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithSuiteName, :args=>3, :names=>[:className, :dictionary], :types=>["@", "@", "@"], :retval=>"@"
    attach_method :isLocationRequiredToCreateForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :isReadOnlyKey, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :keyWithAppleEventCode, :args=>1, :names=>[], :types=>["I"], :retval=>"@"
    attach_method :matchesAppleEventCode, :args=>1, :names=>[], :types=>["I"], :retval=>"B"
    attach_method :selectorForCommand, :args=>1, :names=>[], :types=>["@"], :retval=>":"
    attach_method :suiteName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :superclassDescription, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :supportsCommand, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :typeForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
  end
end
