# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSScriptSuiteRegistry < Cocoa::NSObject
    attach_method :aeteResource, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :appleEventCodeForSuite, :args=>1, :names=>[], :types=>["@"], :retval=>"I"
    attach_method :bundleForSuite, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :classDescriptionWithAppleEventCode, :args=>1, :names=>[], :types=>["I"], :retval=>"@"
    attach_method :classDescriptionsInSuite, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :commandDescriptionWithAppleEventClass, :args=>2, :names=>[:andAppleEventCode], :types=>["I", "I"], :retval=>"@"
    attach_method :commandDescriptionsInSuite, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :loadSuiteWithDictionary, :args=>2, :names=>[:fromBundle], :types=>["@", "@"], :retval=>"v"
    attach_method :loadSuitesFromBundle, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :registerClassDescription, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :registerCommandDescription, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_singular_method :setSharedScriptSuiteRegistry, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_singular_method :sharedScriptSuiteRegistry, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :suiteForAppleEventCode, :args=>1, :names=>[], :types=>["I"], :retval=>"@"
    attach_method :suiteNames, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
