# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSScriptWhoseTest < Cocoa::NSObject
    attach_method :isTrue, :args=>0, :names=>[], :types=>[], :retval=>"B"
  end
end
