# generated by 'rake generate'
require 'cocoa/bindings/NSControl'
module Cocoa
  class NSSegmentedControl < Cocoa::NSControl
    attach_method :imageForSegment, :args=>1, :names=>[], :types=>["q"], :retval=>"@"
    attach_method :imageScalingForSegment, :args=>1, :names=>[], :types=>["q"], :retval=>"Q"
    attach_method :isEnabledForSegment, :args=>1, :names=>[], :types=>["q"], :retval=>"B"
    attach_method :isSelectedForSegment, :args=>1, :names=>[], :types=>["q"], :retval=>"B"
    attach_method :labelForSegment, :args=>1, :names=>[], :types=>["q"], :retval=>"@"
    attach_method :menuForSegment, :args=>1, :names=>[], :types=>["q"], :retval=>"@"
    attach_method :segmentCount, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :segmentStyle, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :selectSegmentWithTag, :args=>1, :names=>[], :types=>["q"], :retval=>"B"
    attach_method :selectedSegment, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :setEnabled, :args=>2, :names=>[:forSegment], :types=>["B", "q"], :retval=>"v"
    attach_method :setImage, :args=>2, :names=>[:forSegment], :types=>["@", "q"], :retval=>"v"
    attach_method :setImageScaling, :args=>2, :names=>[:forSegment], :types=>["Q", "q"], :retval=>"v"
    attach_method :setLabel, :args=>2, :names=>[:forSegment], :types=>["@", "q"], :retval=>"v"
    attach_method :setMenu, :args=>2, :names=>[:forSegment], :types=>["@", "q"], :retval=>"v"
    attach_method :setSegmentCount, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setSegmentStyle, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setSelected, :args=>2, :names=>[:forSegment], :types=>["B", "q"], :retval=>"v"
    attach_method :setSelectedSegment, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setWidth, :args=>2, :names=>[:forSegment], :types=>["d", "q"], :retval=>"v"
    attach_method :widthForSegment, :args=>1, :names=>[], :types=>["q"], :retval=>"d"
  end
end
