# generated by 'rake generate'
require 'cocoa/bindings/NSTextFieldCell'
module Cocoa
  class NSSearchFieldCell < Cocoa::NSTextFieldCell
    attach_method :cancelButtonCell, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :cancelButtonRectForBounds, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"{CGRect={CGPoint=dd}{CGSize=dd}}"
    attach_method :maximumRecents, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :recentSearches, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :recentsAutosaveName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :resetCancelButtonCell, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :resetSearchButtonCell, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :searchButtonCell, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :searchButtonRectForBounds, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"{CGRect={CGPoint=dd}{CGSize=dd}}"
    attach_method :searchMenuTemplate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :searchTextRectForBounds, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"{CGRect={CGPoint=dd}{CGSize=dd}}"
    attach_method :sendsSearchStringImmediately, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :sendsWholeSearchString, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :setCancelButtonCell, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setMaximumRecents, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setRecentSearches, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setRecentsAutosaveName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setSearchButtonCell, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setSearchMenuTemplate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setSendsSearchStringImmediately, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setSendsWholeSearchString, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
  end
end
