# generated by 'rake generate'
require 'cocoa/bindings/NSScriptCommand'
module Cocoa
  class NSSetCommand < Cocoa::NSScriptCommand
    attach_method :keySpecifier, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setReceiversSpecifier, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
