# generated by 'rake generate'
require 'cocoa/bindings/NSTextFieldCell'
module Cocoa
  class NSSecureTextFieldCell < Cocoa::NSTextFieldCell
    attach_method :echosBullets, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :setEchosBullets, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
  end
end
