# generated by 'rake generate'
require 'cocoa/bindings/NSTextField'
module Cocoa
  class NSSearchField < Cocoa::NSTextField
    attach_method :recentSearches, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :recentsAutosaveName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setRecentSearches, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setRecentsAutosaveName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
