# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSShadow < Cocoa::NSObject
    attach_method :init, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :set, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :setShadowBlurRadius, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setShadowColor, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setShadowOffset, :args=>1, :names=>[], :types=>["{CGSize=dd}"], :retval=>"v"
    attach_method :shadowBlurRadius, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :shadowColor, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :shadowOffset, :args=>0, :names=>[], :types=>[], :retval=>"{CGSize=dd}"
  end
end
