# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSSharingService < Cocoa::NSObject
    attach_method :alternateImage, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :canPerformWithItems, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :image, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithTitle, :args=>4, :names=>[:image, :alternateImage, :handler], :types=>["@", "@", "@", "@?"], :retval=>"@"
    attach_method :performWithItems, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_singular_method :sharingServiceNamed, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :sharingServicesForItems, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :title, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
