# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSSortDescriptor < Cocoa::NSObject
    attach_method :ascending, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :comparator, :args=>0, :names=>[], :types=>[], :retval=>"@?"
    attach_method :compareObject, :args=>2, :names=>[:toObject], :types=>["@", "@"], :retval=>"q"
    attach_method :initWithKey, [{:args=>2, :names=>[:ascending], :types=>["@", "B"], :retval=>"@"}, {:args=>3, :names=>[:ascending, :comparator], :types=>["@", "B", "@?"], :retval=>"@"}, {:args=>3, :names=>[:ascending, :selector], :types=>["@", "B", ":"], :retval=>"@"}]
    attach_method :key, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :reversedSortDescriptor, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :selector, :args=>0, :names=>[], :types=>[], :retval=>":"
    attach_singular_method :sortDescriptorWithKey, [{:args=>2, :names=>[:ascending], :types=>["@", "B"], :retval=>"@"}, {:args=>3, :names=>[:ascending, :comparator], :types=>["@", "B", "@?"], :retval=>"@"}, {:args=>3, :names=>[:ascending, :selector], :types=>["@", "B", ":"], :retval=>"@"}]
  end
end
