# generated by 'rake generate'
require 'cocoa/bindings/NSPort'
module Cocoa
  class NSSocketPort < Cocoa::NSPort
    attach_method :address, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :init, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initRemoteWithProtocolFamily, :args=>4, :names=>[:socketType, :protocol, :address], :types=>["i", "i", "i", "@"], :retval=>"@"
    attach_method :initRemoteWithTCPPort, :args=>2, :names=>[:host], :types=>["S", "@"], :retval=>"@"
    attach_method :initWithProtocolFamily, [{:args=>4, :names=>[:socketType, :protocol, :address], :types=>["i", "i", "i", "@"], :retval=>"@"}, {:args=>4, :names=>[:socketType, :protocol, :socket], :types=>["i", "i", "i", "i"], :retval=>"@"}]
    attach_method :initWithTCPPort, :args=>1, :names=>[], :types=>["S"], :retval=>"@"
    attach_method :protocol, :args=>0, :names=>[], :types=>[], :retval=>"i"
    attach_method :protocolFamily, :args=>0, :names=>[], :types=>[], :retval=>"i"
    attach_method :socket, :args=>0, :names=>[], :types=>[], :retval=>"i"
    attach_method :socketType, :args=>0, :names=>[], :types=>[], :retval=>"i"
  end
end
