# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSSpeechSynthesizer < Cocoa::NSObject
    attach_method :addSpeechDictionary, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_singular_method :attributesForVoice, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :availableVoices, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :continueSpeaking, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_singular_method :defaultVoice, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithVoice, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :isAnyApplicationSpeaking, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isSpeaking, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :objectForProperty, :args=>2, :names=>["error"], :types=>["@", "^@"], :retval=>"@"
    attach_method :pauseSpeakingAtBoundary, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :phonemesFromText, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :rate, :args=>0, :names=>[], :types=>[], :retval=>"f"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setObject, :args=>3, :names=>["forProperty", "error"], :types=>["@", "@", "^@"], :retval=>"B"
    attach_method :setRate, :args=>1, :names=>[], :types=>["f"], :retval=>"v"
    attach_method :setUsesFeedbackWindow, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setVoice, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :setVolume, :args=>1, :names=>[], :types=>["f"], :retval=>"v"
    attach_method :startSpeakingString, [{:args=>1, :names=>[], :types=>["@"], :retval=>"B"}, {:args=>2, :names=>["toURL"], :types=>["@", "@"], :retval=>"B"}]
    attach_method :stopSpeaking, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :stopSpeakingAtBoundary, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :usesFeedbackWindow, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :voice, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :volume, :args=>0, :names=>[], :types=>[], :retval=>"f"
  end
end
