# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSSpeechRecognizer < Cocoa::NSObject
    attach_method :blocksOtherRecognizers, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :commands, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :displayedCommandsTitle, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :init, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :listensInForegroundOnly, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :setBlocksOtherRecognizers, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setCommands, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDisplayedCommandsTitle, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setListensInForegroundOnly, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :startListening, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :stopListening, :args=>0, :names=>[], :types=>[], :retval=>"v"
  end
end
