# generated by 'rake generate'
require 'cocoa/bindings/NSScriptWhoseTest'
module Cocoa
  class NSSpecifierTest < Cocoa::NSScriptWhoseTest
    attach_method :initWithObjectSpecifier, :args=>3, :names=>["comparisonOperator", "testObject"], :types=>["@", "Q", "@"], :retval=>"@"
  end
end
