# generated by 'rake generate'
require 'cocoa/bindings/NSView'
module Cocoa
  class NSSplitView < Cocoa::NSView
    attach_method :adjustSubviews, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :autosaveName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :dividerColor, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :dividerStyle, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :dividerThickness, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :drawDividerInRect, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"v"
    attach_method :holdingPriorityForSubviewAtIndex, :args=>1, :names=>[], :types=>["q"], :retval=>"f"
    attach_method :isPaneSplitter, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isSubviewCollapsed, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :isVertical, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :maxPossiblePositionOfDividerAtIndex, :args=>1, :names=>[], :types=>["q"], :retval=>"d"
    attach_method :minPossiblePositionOfDividerAtIndex, :args=>1, :names=>[], :types=>["q"], :retval=>"d"
    attach_method :setAutosaveName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDividerStyle, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setHoldingPriority, :args=>2, :names=>["forSubviewAtIndex"], :types=>["f", "q"], :retval=>"v"
    attach_method :setIsPaneSplitter, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setPosition, :args=>2, :names=>["ofDividerAtIndex"], :types=>["d", "q"], :retval=>"v"
    attach_method :setVertical, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
  end
end
