# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSStatusBar < Cocoa::NSObject
    attach_method :isVertical, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :removeStatusItem, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :statusItemWithLength, :args=>1, :names=>[], :types=>["d"], :retval=>"@"
    attach_singular_method :systemStatusBar, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :thickness, :args=>0, :names=>[], :types=>[], :retval=>"d"
  end
end
