# generated by 'rake generate'
require 'cocoa/bindings/NSView'
module Cocoa
  class NSTableCellView < Cocoa::NSView
    attach_method :backgroundStyle, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :draggingImageComponents, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :imageView, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :objectValue, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :rowSizeStyle, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :setBackgroundStyle, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setImageView, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setObjectValue, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setRowSizeStyle, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setTextField, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :textField, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
