# generated by 'rake generate'
require 'cocoa/bindings/NSView'
module Cocoa
  class NSTableHeaderView < Cocoa::NSView
    attach_method :columnAtPoint, :args=>1, :names=>[], :types=>["{CGPoint=dd}"], :retval=>"q"
    attach_method :draggedColumn, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :draggedDistance, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :headerRectOfColumn, :args=>1, :names=>[], :types=>["q"], :retval=>"{CGRect={CGPoint=dd}{CGSize=dd}}"
    attach_method :resizedColumn, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :setTableView, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :tableView, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
