# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSTabViewItem < Cocoa::NSObject
    attach_method :color, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :drawLabel, :args=>2, :names=>[:inRect], :types=>["B", "{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"v"
    attach_method :identifier, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithIdentifier, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :initialFirstResponder, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :label, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setColor, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setIdentifier, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setInitialFirstResponder, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setLabel, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setToolTip, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setView, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :sizeOfLabel, :args=>1, :names=>[], :types=>["B"], :retval=>"{CGSize=dd}"
    attach_method :tabState, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :tabView, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :toolTip, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :view, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
