# generated by 'rake generate'
require 'cocoa/bindings/NSView'
module Cocoa
  class NSTableRowView < Cocoa::NSView
    attach_method :backgroundColor, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :draggingDestinationFeedbackStyle, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :drawBackgroundInRect, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"v"
    attach_method :drawDraggingDestinationFeedbackInRect, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"v"
    attach_method :drawSelectionInRect, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"v"
    attach_method :drawSeparatorInRect, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"v"
    attach_method :indentationForDropOperation, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_method :interiorBackgroundStyle, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :isEmphasized, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isFloating, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isGroupRowStyle, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isSelected, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :isTargetForDropOperation, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :numberOfColumns, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :selectionHighlightStyle, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :setBackgroundColor, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDraggingDestinationFeedbackStyle, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setEmphasized, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setFloating, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setGroupRowStyle, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setIndentationForDropOperation, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setSelected, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setSelectionHighlightStyle, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :setTargetForDropOperation, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :viewAtColumn, :args=>1, :names=>[], :types=>["q"], :retval=>"@"
  end
end
