# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSTask < Cocoa::NSObject
    attach_method :arguments, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :currentDirectoryPath, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :environment, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :init, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :interrupt, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :isRunning, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :launch, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :launchPath, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :launchedTaskWithLaunchPath, :args=>2, :names=>[:arguments], :types=>["@", "@"], :retval=>"@"
    attach_method :processIdentifier, :args=>0, :names=>[], :types=>[], :retval=>"i"
    attach_method :resume, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :setArguments, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setCurrentDirectoryPath, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setEnvironment, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setLaunchPath, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setStandardError, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setStandardInput, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setStandardOutput, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setTerminationHandler, :args=>1, :names=>[], :types=>["@?"], :retval=>"v"
    attach_method :standardError, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :standardInput, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :standardOutput, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :suspend, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :terminate, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :terminationHandler, :args=>0, :names=>[], :types=>[], :retval=>"@?"
    attach_method :terminationReason, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :terminationStatus, :args=>0, :names=>[], :types=>[], :retval=>"i"
    attach_method :waitUntilExit, :args=>0, :names=>[], :types=>[], :retval=>"v"
  end
end
