# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSTextList < Cocoa::NSObject
    attach_method :initWithMarkerFormat, :args=>2, :names=>[:options], :types=>["@", "Q"], :retval=>"@"
    attach_method :listOptions, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :markerForItemNumber, :args=>1, :names=>[], :types=>["q"], :retval=>"@"
    attach_method :markerFormat, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setStartingItemNumber, :args=>1, :names=>[], :types=>["q"], :retval=>"v"
    attach_method :startingItemNumber, :args=>0, :names=>[], :types=>[], :retval=>"q"
  end
end
