# generated by 'rake generate'
require 'cocoa/bindings/NSActionCell'
module Cocoa
  class NSTextFieldCell < Cocoa::NSActionCell
    attach_method :allowedInputSourceLocales, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :backgroundColor, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :bezelStyle, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :drawsBackground, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :placeholderAttributedString, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :placeholderString, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setAllowedInputSourceLocales, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setBackgroundColor, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setBezelStyle, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setDrawsBackground, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setPlaceholderAttributedString, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setPlaceholderString, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setTextColor, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setUpFieldEditorAttributes, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :setWantsNotificationForMarkedText, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :textColor, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
