# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSTextInputContext < Cocoa::NSObject
    attach_method :acceptsGlyphInfo, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :activate, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :allowedInputSourceLocales, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :client, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :currentInputContext, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :deactivate, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :discardMarkedText, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :handleEvent, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :initWithClient, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :invalidateCharacterCoordinates, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :keyboardInputSources, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :localizedNameForInputSource, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :selectedKeyboardInputSource, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setAcceptsGlyphInfo, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setAllowedInputSourceLocales, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setSelectedKeyboardInputSource, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
