# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSTextAttachment < Cocoa::NSObject
    attach_method :attachmentCell, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :fileWrapper, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithFileWrapper, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :setAttachmentCell, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setFileWrapper, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
