# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSTextCheckingResult < Cocoa::NSObject
    attach_method :URL, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :addressCheckingResultWithRange, :args=>2, :names=>[:components], :types=>["{_NSRange=QQ}", "@"], :retval=>"@"
    attach_method :addressComponents, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :components, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :correctionCheckingResultWithRange, :args=>2, :names=>[:replacementString], :types=>["{_NSRange=QQ}", "@"], :retval=>"@"
    attach_singular_method :dashCheckingResultWithRange, :args=>2, :names=>[:replacementString], :types=>["{_NSRange=QQ}", "@"], :retval=>"@"
    attach_method :date, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :dateCheckingResultWithRange, [{:args=>2, :names=>[:date], :types=>["{_NSRange=QQ}", "@"], :retval=>"@"}, {:args=>4, :names=>[:date, :timeZone, :duration], :types=>["{_NSRange=QQ}", "@", "@", "d"], :retval=>"@"}]
    attach_method :duration, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_singular_method :grammarCheckingResultWithRange, :args=>2, :names=>[:details], :types=>["{_NSRange=QQ}", "@"], :retval=>"@"
    attach_method :grammarDetails, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :linkCheckingResultWithRange, :args=>2, :names=>[:URL], :types=>["{_NSRange=QQ}", "@"], :retval=>"@"
    attach_method :numberOfRanges, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :orthography, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :orthographyCheckingResultWithRange, :args=>2, :names=>[:orthography], :types=>["{_NSRange=QQ}", "@"], :retval=>"@"
    attach_method :phoneNumber, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :phoneNumberCheckingResultWithRange, :args=>2, :names=>[:phoneNumber], :types=>["{_NSRange=QQ}", "@"], :retval=>"@"
    attach_singular_method :quoteCheckingResultWithRange, :args=>2, :names=>[:replacementString], :types=>["{_NSRange=QQ}", "@"], :retval=>"@"
    attach_method :range, :args=>0, :names=>[], :types=>[], :retval=>"{_NSRange=QQ}"
    attach_method :rangeAtIndex, :args=>1, :names=>[], :types=>["Q"], :retval=>"{_NSRange=QQ}"
    attach_method :regularExpression, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :regularExpressionCheckingResultWithRanges, :args=>3, :names=>[:count, :regularExpression], :types=>["^{_NSRange=QQ}", "Q", "@"], :retval=>"@"
    attach_singular_method :replacementCheckingResultWithRange, :args=>2, :names=>[:replacementString], :types=>["{_NSRange=QQ}", "@"], :retval=>"@"
    attach_method :replacementString, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :resultByAdjustingRangesWithOffset, :args=>1, :names=>[], :types=>["q"], :retval=>"@"
    attach_method :resultType, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_singular_method :spellCheckingResultWithRange, :args=>1, :names=>[], :types=>["{_NSRange=QQ}"], :retval=>"@"
    attach_method :timeZone, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :transitInformationCheckingResultWithRange, :args=>2, :names=>[:components], :types=>["{_NSRange=QQ}", "@"], :retval=>"@"
  end
end
