# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSTimer < Cocoa::NSObject
    attach_method :fire, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :fireDate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithFireDate, :args=>6, :names=>[:interval, :target, :selector, :userInfo, :repeats], :types=>["@", "d", "@", ":", "@", "B"], :retval=>"@"
    attach_method :invalidate, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :isValid, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_singular_method :scheduledTimerWithTimeInterval, [{:args=>3, :names=>[:invocation, :repeats], :types=>["d", "@", "B"], :retval=>"@"}, {:args=>5, :names=>[:target, :selector, :userInfo, :repeats], :types=>["d", "@", ":", "@", "B"], :retval=>"@"}]
    attach_method :setFireDate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :timeInterval, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_singular_method :timerWithTimeInterval, [{:args=>3, :names=>[:invocation, :repeats], :types=>["d", "@", "B"], :retval=>"@"}, {:args=>5, :names=>[:target, :selector, :userInfo, :repeats], :types=>["d", "@", ":", "@", "B"], :retval=>"@"}]
    attach_method :userInfo, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
