# generated by 'rake generate'
require 'cocoa/bindings/NSToolbarItem'
module Cocoa
  class NSToolbarItemGroup < Cocoa::NSToolbarItem
    attach_method :setSubitems, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :subitems, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
