# generated by 'rake generate'
require 'cocoa/bindings/NSTextField'
module Cocoa
  class NSTokenField < Cocoa::NSTextField
    attach_method :completionDelay, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_singular_method :defaultCompletionDelay, :args=>0, :names=>[], :types=>[], :retval=>"d"
    attach_singular_method :defaultTokenizingCharacterSet, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setCompletionDelay, :args=>1, :names=>[], :types=>["d"], :retval=>"v"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setTokenStyle, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :setTokenizingCharacterSet, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :tokenStyle, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :tokenizingCharacterSet, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
