# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSTouch < Cocoa::NSObject
    attach_method :device, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :deviceSize, :args=>0, :names=>[], :types=>[], :retval=>"{CGSize=dd}"
    attach_method :identity, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :isResting, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :normalizedPosition, :args=>0, :names=>[], :types=>[], :retval=>"{CGPoint=dd}"
    attach_method :phase, :args=>0, :names=>[], :types=>[], :retval=>"Q"
  end
end
