# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSTreeNode < Cocoa::NSObject
    attach_method :childNodes, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :descendantNodeAtIndexPath, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :indexPath, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithRepresentedObject, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :isLeaf, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :mutableChildNodes, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :parentNode, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :representedObject, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :sortWithSortDescriptors, :args=>2, :names=>["recursively"], :types=>["@", "B"], :retval=>"v"
    attach_singular_method :treeNodeWithRepresentedObject, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
  end
end
