# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSUbiquitousKeyValueStore < Cocoa::NSObject
    attach_method :arrayForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :boolForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :dataForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :defaultStore, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :dictionaryForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :dictionaryRepresentation, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :doubleForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"d"
    attach_method :longLongForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"q"
    attach_method :objectForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :removeObjectForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setArray, :args=>2, :names=>["forKey"], :types=>["@", "@"], :retval=>"v"
    attach_method :setBool, :args=>2, :names=>["forKey"], :types=>["B", "@"], :retval=>"v"
    attach_method :setData, :args=>2, :names=>["forKey"], :types=>["@", "@"], :retval=>"v"
    attach_method :setDictionary, :args=>2, :names=>["forKey"], :types=>["@", "@"], :retval=>"v"
    attach_method :setDouble, :args=>2, :names=>["forKey"], :types=>["d", "@"], :retval=>"v"
    attach_method :setLongLong, :args=>2, :names=>["forKey"], :types=>["q", "@"], :retval=>"v"
    attach_method :setObject, :args=>2, :names=>["forKey"], :types=>["@", "@"], :retval=>"v"
    attach_method :setString, :args=>2, :names=>["forKey"], :types=>["@", "@"], :retval=>"v"
    attach_method :stringForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :synchronize, :args=>0, :names=>[], :types=>[], :retval=>"B"
  end
end
