# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSURLHandle < Cocoa::NSObject
    attach_singular_method :URLHandleClassForURL, :args=>1, :names=>[], :types=>["@"], :retval=>"#"
    attach_method :addClient, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :availableResourceData, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :backgroundLoadDidFailWithReason, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :beginLoadInBackground, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_singular_method :cachedHandleForURL, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :canInitWithURL, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :cancelLoadInBackground, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :didLoadBytes, :args=>2, :names=>[:loadComplete], :types=>["@", "B"], :retval=>"v"
    attach_method :endLoadInBackground, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :expectedResourceDataSize, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :failureReason, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :flushCachedData, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :initWithURL, :args=>2, :names=>[:cached], :types=>["@", "B"], :retval=>"@"
    attach_method :loadInBackground, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :loadInForeground, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :propertyForKey, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :propertyForKeyIfAvailable, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :registerURLHandleClass, :args=>1, :names=>[], :types=>["#"], :retval=>"v"
    attach_method :removeClient, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :resourceData, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :status, :args=>0, :names=>[], :types=>[], :retval=>"Q"
    attach_method :writeData, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :writeProperty, :args=>2, :names=>[:forKey], :types=>["@", "@"], :retval=>"B"
  end
end
