# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSURLProtocol < Cocoa::NSObject
    attach_method :cachedResponse, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :canInitWithRequest, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_singular_method :canonicalRequestForRequest, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :client, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithRequest, :args=>3, :names=>["cachedResponse", "client"], :types=>["@", "@", "@"], :retval=>"@"
    attach_singular_method :propertyForKey, :args=>2, :names=>["inRequest"], :types=>["@", "@"], :retval=>"@"
    attach_singular_method :registerClass, :args=>1, :names=>[], :types=>["#"], :retval=>"B"
    attach_singular_method :removePropertyForKey, :args=>2, :names=>["inRequest"], :types=>["@", "@"], :retval=>"v"
    attach_method :request, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_singular_method :requestIsCacheEquivalent, :args=>2, :names=>["toRequest"], :types=>["@", "@"], :retval=>"B"
    attach_singular_method :setProperty, :args=>3, :names=>["forKey", "inRequest"], :types=>["@", "@", "@"], :retval=>"v"
    attach_method :startLoading, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :stopLoading, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_singular_method :unregisterClass, :args=>1, :names=>[], :types=>["#"], :retval=>"v"
  end
end
