# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSURLProtectionSpace < Cocoa::NSObject
    attach_method :authenticationMethod, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :distinguishedNames, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :host, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithHost, :args=>5, :names=>["port", "protocol", "realm", "authenticationMethod"], :types=>["@", "q", "@", "@", "@"], :retval=>"@"
    attach_method :initWithProxyHost, :args=>5, :names=>["port", "type", "realm", "authenticationMethod"], :types=>["@", "q", "@", "@", "@"], :retval=>"@"
    attach_method :isProxy, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :port, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :protocol, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :proxyType, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :realm, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :receivesCredentialSecurely, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :serverTrust, :args=>0, :names=>[], :types=>[], :retval=>"^{OpaqueSecTrustRef=}"
  end
end
