# generated by 'rake generate'
require 'cocoa/bindings/NSUserScriptTask'
module Cocoa
  class NSUserAppleScriptTask < Cocoa::NSUserScriptTask
    attach_method :executeWithAppleEvent, :args=>2, :names=>["completionHandler"], :types=>["@", "@?"], :retval=>"v"
  end
end
