# generated by 'rake generate'
require 'cocoa/bindings/NSController'
module Cocoa
  class NSUserDefaultsController < Cocoa::NSController
    attach_method :appliesImmediately, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :defaults, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :hasUnappliedChanges, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :initWithDefaults, :args=>2, :names=>["initialValues"], :types=>["@", "@"], :retval=>"@"
    attach_method :initialValues, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :revert, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :revertToInitialValues, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :save, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setAppliesImmediately, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setInitialValues, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_singular_method :sharedUserDefaultsController, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :values, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
