# generated by 'rake generate'
require 'cocoa/bindings/NSUserScriptTask'
module Cocoa
  class NSUserUnixTask < Cocoa::NSUserScriptTask
    attach_method :executeWithArguments, :args=>2, :names=>["completionHandler"], :types=>["@", "@?"], :retval=>"v"
    attach_method :setStandardError, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setStandardInput, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setStandardOutput, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :standardError, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :standardInput, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :standardOutput, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
