# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSUserNotificationCenter < Cocoa::NSObject
    attach_singular_method :defaultUserNotificationCenter, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :deliverNotification, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :deliveredNotifications, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :removeAllDeliveredNotifications, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :removeDeliveredNotification, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :removeScheduledNotification, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :scheduleNotification, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :scheduledNotifications, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setScheduledNotifications, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
