# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSUUID < Cocoa::NSObject
    attach_singular_method :UUID, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :UUIDString, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :getUUIDBytes, :args=>1, :names=>[], :types=>["*"], :retval=>"v"
    attach_method :init, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithUUIDBytes, :args=>1, :names=>[], :types=>["*"], :retval=>"@"
    attach_method :initWithUUIDString, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
  end
end
