# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSValue < Cocoa::NSObject
    attach_method :CATransform3DValue, :args=>0, :names=>[], :types=>[], :retval=>"{CATransform3D=dddddddddddddddd}"
    attach_method :getValue, :args=>1, :names=>[], :types=>["^v"], :retval=>"v"
    attach_method :initWithBytes, :args=>2, :names=>["objCType"], :types=>["^v", "*"], :retval=>"@"
    attach_method :isEqualToValue, :args=>1, :names=>[], :types=>["@"], :retval=>"B"
    attach_method :nonretainedObjectValue, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :objCType, :args=>0, :names=>[], :types=>[], :retval=>"*"
    attach_method :pointValue, :args=>0, :names=>[], :types=>[], :retval=>"{CGPoint=dd}"
    attach_method :pointerValue, :args=>0, :names=>[], :types=>[], :retval=>"^v"
    attach_method :rangeValue, :args=>0, :names=>[], :types=>[], :retval=>"{_NSRange=QQ}"
    attach_method :rectValue, :args=>0, :names=>[], :types=>[], :retval=>"{CGRect={CGPoint=dd}{CGSize=dd}}"
    attach_method :sizeValue, :args=>0, :names=>[], :types=>[], :retval=>"{CGSize=dd}"
    attach_singular_method :value, :args=>2, :names=>["withObjCType"], :types=>["^v", "*"], :retval=>"@"
    attach_singular_method :valueWithBytes, :args=>2, :names=>["objCType"], :types=>["^v", "*"], :retval=>"@"
    attach_singular_method :valueWithCATransform3D, :args=>1, :names=>[], :types=>["{CATransform3D=dddddddddddddddd}"], :retval=>"@"
    attach_singular_method :valueWithNonretainedObject, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :valueWithPoint, :args=>1, :names=>[], :types=>["{CGPoint=dd}"], :retval=>"@"
    attach_singular_method :valueWithPointer, :args=>1, :names=>[], :types=>["^v"], :retval=>"@"
    attach_singular_method :valueWithRange, :args=>1, :names=>[], :types=>["{_NSRange=QQ}"], :retval=>"@"
    attach_singular_method :valueWithRect, :args=>1, :names=>[], :types=>["{CGRect={CGPoint=dd}{CGSize=dd}}"], :retval=>"@"
    attach_singular_method :valueWithSize, :args=>1, :names=>[], :types=>["{CGSize=dd}"], :retval=>"@"
  end
end
