# generated by 'rake generate'
require 'cocoa/bindings/NSAnimation'
module Cocoa
  class NSViewAnimation < Cocoa::NSAnimation
    attach_method :initWithViewAnimations, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :setViewAnimations, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :viewAnimations, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
