# generated by 'rake generate'
require 'cocoa/bindings/NSResponder'
module Cocoa
  class NSViewController < Cocoa::NSResponder
    attach_method :commitEditing, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :commitEditingWithDelegate, :args=>3, :names=>["didCommitSelector", "contextInfo"], :types=>["@", ":", "^v"], :retval=>"v"
    attach_method :discardEditing, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :initWithNibName, :args=>2, :names=>["bundle"], :types=>["@", "@"], :retval=>"@"
    attach_method :loadView, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :nibBundle, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :nibName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :representedObject, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setRepresentedObject, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setTitle, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setView, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :title, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :view, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
