# generated by 'rake generate'
require 'cocoa/bindings/NSResponder'
module Cocoa
  class NSWindowController < Cocoa::NSResponder
    attach_method :close, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :document, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithWindow, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :initWithWindowNibName, [{:args=>1, :names=>[], :types=>["@"], :retval=>"@"}, {:args=>2, :names=>[:owner], :types=>["@", "@"], :retval=>"@"}]
    attach_method :initWithWindowNibPath, :args=>2, :names=>[:owner], :types=>["@", "@"], :retval=>"@"
    attach_method :isWindowLoaded, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :loadWindow, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :owner, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setDocument, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setDocumentEdited, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setShouldCascadeWindows, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setShouldCloseDocument, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setWindow, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setWindowFrameAutosaveName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :shouldCascadeWindows, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :shouldCloseDocument, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :showWindow, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :synchronizeWindowTitleWithDocumentName, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :window, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :windowDidLoad, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :windowFrameAutosaveName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :windowNibName, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :windowNibPath, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :windowTitleForDocumentDisplayName, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :windowWillLoad, :args=>0, :names=>[], :types=>[], :retval=>"v"
  end
end
