# generated by 'rake generate'
require 'cocoa/bindings/NSXMLNode'
module Cocoa
  class NSXMLElement < Cocoa::NSXMLNode
    attach_method :addAttribute, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :addChild, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :addNamespace, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :attributeForLocalName, :args=>2, :names=>["URI"], :types=>["@", "@"], :retval=>"@"
    attach_method :attributeForName, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :attributes, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :elementsForLocalName, :args=>2, :names=>["URI"], :types=>["@", "@"], :retval=>"@"
    attach_method :elementsForName, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :initWithName, [{:args=>1, :names=>[], :types=>["@"], :retval=>"@"}, {:args=>2, :names=>["URI"], :types=>["@", "@"], :retval=>"@"}, {:args=>2, :names=>["stringValue"], :types=>["@", "@"], :retval=>"@"}]
    attach_method :initWithXMLString, :args=>2, :names=>["error"], :types=>["@", "^@"], :retval=>"@"
    attach_method :insertChild, :args=>2, :names=>["atIndex"], :types=>["@", "Q"], :retval=>"v"
    attach_method :insertChildren, :args=>2, :names=>["atIndex"], :types=>["@", "Q"], :retval=>"v"
    attach_method :namespaceForPrefix, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :namespaces, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :normalizeAdjacentTextNodesPreservingCDATA, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :removeAttributeForName, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :removeChildAtIndex, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :removeNamespaceForPrefix, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :replaceChildAtIndex, :args=>2, :names=>["withNode"], :types=>["Q", "@"], :retval=>"v"
    attach_method :resolveNamespaceForName, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :resolvePrefixForNamespaceURI, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :setAttributes, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setAttributesAsDictionary, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setAttributesWithDictionary, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setChildren, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setNamespaces, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
  end
end
