# generated by 'rake generate'
require 'cocoa/bindings/NSXMLNode'
module Cocoa
  class NSXMLDTD < Cocoa::NSXMLNode
    attach_method :addChild, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :attributeDeclarationForName, :args=>2, :names=>[:elementName], :types=>["@", "@"], :retval=>"@"
    attach_method :elementDeclarationForName, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :entityDeclarationForName, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :initWithContentsOfURL, :args=>3, :names=>[:options, :error], :types=>["@", "Q", "^@"], :retval=>"@"
    attach_method :initWithData, :args=>3, :names=>[:options, :error], :types=>["@", "Q", "^@"], :retval=>"@"
    attach_method :insertChild, :args=>2, :names=>[:atIndex], :types=>["@", "Q"], :retval=>"v"
    attach_method :insertChildren, :args=>2, :names=>[:atIndex], :types=>["@", "Q"], :retval=>"v"
    attach_method :notationDeclarationForName, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_singular_method :predefinedEntityDeclarationForName, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :publicID, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :removeChildAtIndex, :args=>1, :names=>[], :types=>["Q"], :retval=>"v"
    attach_method :replaceChildAtIndex, :args=>2, :names=>[:withNode], :types=>["Q", "@"], :retval=>"v"
    attach_method :setChildren, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setPublicID, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setSystemID, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :systemID, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
