# generated by 'rake generate'
require 'cocoa/bindings/NSObject'
module Cocoa
  class NSXMLParser < Cocoa::NSObject
    attach_method :abortParsing, :args=>0, :names=>[], :types=>[], :retval=>"v"
    attach_method :columnNumber, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :delegate, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :initWithContentsOfURL, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :initWithData, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :initWithStream, :args=>1, :names=>[], :types=>["@"], :retval=>"@"
    attach_method :lineNumber, :args=>0, :names=>[], :types=>[], :retval=>"q"
    attach_method :parse, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :parserError, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :publicID, :args=>0, :names=>[], :types=>[], :retval=>"@"
    attach_method :setDelegate, :args=>1, :names=>[], :types=>["@"], :retval=>"v"
    attach_method :setShouldProcessNamespaces, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setShouldReportNamespacePrefixes, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :setShouldResolveExternalEntities, :args=>1, :names=>[], :types=>["B"], :retval=>"v"
    attach_method :shouldProcessNamespaces, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :shouldReportNamespacePrefixes, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :shouldResolveExternalEntities, :args=>0, :names=>[], :types=>[], :retval=>"B"
    attach_method :systemID, :args=>0, :names=>[], :types=>[], :retval=>"@"
  end
end
